/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID aduae260-lap)
#  Generated on:      Wed Sep 26 11:52:34 2018
#  Design:            c1908
#  Command:           saveNetlist -module bottom outputs/bottom_j.v
###############################################################
*/
/*
###############################################################
#  Generated by:      Cadence Innovus 17.12-s095_1
#  OS:                Linux x86_64(Host ID aduae260-lap)
#  Generated on:      Fri Mar 16 16:03:08 2018
#  Design:            c1908
#  Command:           saveDesign database/design.final.enc
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 17.20-p003_1
// Generated on: Mar 16 2018 16:02:52 +04 (Mar 16 2018 12:02:52 UTC)
// Verification Directory fv/c1908 
module bottom (
	G101, 
	G104, 
	G107, 
	G110, 
	G113, 
	G116, 
	G119, 
	G122, 
	G125, 
	G128, 
	G131, 
	G134, 
	G137, 
	G140, 
	G146, 
	G210, 
	G214, 
	G217, 
	G221, 
	G224, 
	G227, 
	G234, 
	G237, 
	G469, 
	G472, 
	G475, 
	G900, 
	G902, 
	G953, 
	g41179_ZN, 
	g40971_ZN, 
	g40975_ZN, 
	g40970_ZN, 
	g40966_ZN, 
	g40976_ZN, 
	g40981_ZN, 
	g40980_ZN, 
	g41186_ZN, 
	g40982_ZN, 
	g41114_ZN, 
	g41103_ZN, 
	g41192_ZN, 
	g40983_ZN, 
	g41117_ZN, 
	g40993_ZN, 
	g41190_ZN, 
	g41006_ZN, 
	g41002_ZN, 
	g41032_ZN, 
	g41039_ZN, 
	g41085_ZN, 
	g41072_ZN, 
	g41066_ZN, 
	g41062_ZN, 
	g41029_ZN, 
	g41028_ZN, 
	g41024_ZN, 
	g41077_ZN, 
	g41035_ZN, 
	g41036_ZN, 
	g41037_ZN, 
	g41054_ZN, 
	g41049_ZN, 
	g41065_ZN, 
	g41067_ZN, 
	g41086_ZN, 
	g41134_ZN, 
	g41055_ZN, 
	g41064_ZN, 
	g41060_ZN, 
	g41079_ZN, 
	g41160_ZN, 
	g41075_ZN, 
	g41070_ZN, 
	g41073_ZN, 
	g41092_ZN, 
	g41131_ZN, 
	g41108_ZN, 
	g41094_ZN, 
	g41144_ZN, 
	g41109_ZN, 
	g41096_ZN, 
	g41098_ZN, 
	g41107_ZN, 
	g41123_ZN, 
	g41137_ZN, 
	g41112_ZN, 
	g41181_ZN, 
	g41129_ZN, 
	g41122_ZN, 
	g41159_ZN, 
	g41175_Z, 
	g41169_Z, 
	g41162_ZN, 
	g41157_ZN, 
	g41183_ZN, 
	g41176_ZN, 
	g41165_ZN, 
	g41187_ZN, 
	G9, 
	G30, 
	G48, 
	G15, 
	G21, 
	G27, 
	G36, 
	G42, 
	G51, 
	G54, 
	G60, 
	G66, 
	G72, 
	G57, 
	g40959_A1, 
	g40965_A, 
	g40973_A1, 
	g40965_B1, 
	g40983_A, 
	g40985_A1, 
	g40986_A, 
	g40989_A1, 
	g40993_A1, 
	g41002_A, 
	g40985_A3, 
	g40985_A2, 
	g40986_B1, 
	g40985_A4, 
	g40989_A2, 
	g40989_A3, 
	g41006_A2, 
	g41006_A1, 
	g41032_A, 
	g41029_A1, 
	g41024_A1, 
	g41013_A, 
	g41016_A, 
	g41046_A1, 
	g41037_A2, 
	g41036_A2, 
	g41049_A, 
	g41037_A1, 
	g41067_A, 
	g41060_A, 
	g41029_A2, 
	g41054_B1, 
	g41075_A, 
	g41055_A2, 
	g41044_A3, 
	g41024_A2, 
	g41028_A3, 
	g41071_A1, 
	g41039_A3, 
	g41090_A, 
	g41086_A1, 
	g41066_A2, 
	g41092_B, 
	g41092_C1, 
	g41096_A, 
	g40966_A, 
	g41107_A1, 
	g41103_A, 
	g41119_A1, 
	g41100_B, 
	g41131_A, 
	g41122_B, 
	g41126_A, 
	g41126_B, 
	g41092_C2, 
	g41114_B, 
	g41096_B, 
	g41107_A2, 
	g41142_A, 
	g41073_A2, 
	g41138_B, 
	g40982_A2, 
	g41098_A2, 
	g41140_B, 
	g41140_A, 
	g41137_A, 
	g40966_C2, 
	g41183_A1, 
	g41073_A3, 
	g41123_A);
   input G101;
   input G104;
   input G107;
   input G110;
   input G113;
   input G116;
   input G119;
   input G122;
   input G125;
   input G128;
   input G131;
   input G134;
   input G137;
   input G140;
   input G146;
   input G210;
   input G214;
   input G217;
   input G221;
   input G224;
   input G227;
   input G234;
   input G237;
   input G469;
   input G472;
   input G475;
   input G900;
   input G902;
   input G953;
   input g41179_ZN;
   input g40971_ZN;
   input g40975_ZN;
   input g40970_ZN;
   input g40966_ZN;
   input g40976_ZN;
   input g40981_ZN;
   input g40980_ZN;
   input g41186_ZN;
   input g40982_ZN;
   input g41114_ZN;
   input g41103_ZN;
   input g41192_ZN;
   input g40983_ZN;
   input g41117_ZN;
   input g40993_ZN;
   input g41190_ZN;
   input g41006_ZN;
   input g41002_ZN;
   input g41032_ZN;
   input g41039_ZN;
   input g41085_ZN;
   input g41072_ZN;
   input g41066_ZN;
   input g41062_ZN;
   input g41029_ZN;
   input g41028_ZN;
   input g41024_ZN;
   input g41077_ZN;
   input g41035_ZN;
   input g41036_ZN;
   input g41037_ZN;
   input g41054_ZN;
   input g41049_ZN;
   input g41065_ZN;
   input g41067_ZN;
   input g41086_ZN;
   input g41134_ZN;
   input g41055_ZN;
   input g41064_ZN;
   input g41060_ZN;
   input g41079_ZN;
   input g41160_ZN;
   input g41075_ZN;
   input g41070_ZN;
   input g41073_ZN;
   input g41092_ZN;
   input g41131_ZN;
   input g41108_ZN;
   input g41094_ZN;
   input g41144_ZN;
   input g41109_ZN;
   input g41096_ZN;
   input g41098_ZN;
   input g41107_ZN;
   input g41123_ZN;
   input g41137_ZN;
   input g41112_ZN;
   input g41181_ZN;
   input g41129_ZN;
   input g41122_ZN;
   input g41159_ZN;
   input g41175_Z;
   input g41169_Z;
   input g41162_ZN;
   input g41157_ZN;
   input g41183_ZN;
   input g41176_ZN;
   input g41165_ZN;
   input g41187_ZN;
   output G9;
   output G30;
   output G48;
   output G15;
   output G21;
   output G27;
   output G36;
   output G42;
   output G51;
   output G54;
   output G60;
   output G66;
   output G72;
   output G57;
   output g40959_A1;
   output g40965_A;
   output g40973_A1;
   output g40965_B1;
   output g40983_A;
   output g40985_A1;
   output g40986_A;
   output g40989_A1;
   output g40993_A1;
   output g41002_A;
   output g40985_A3;
   output g40985_A2;
   output g40986_B1;
   output g40985_A4;
   output g40989_A2;
   output g40989_A3;
   output g41006_A2;
   output g41006_A1;
   output g41032_A;
   output g41029_A1;
   output g41024_A1;
   output g41013_A;
   output g41016_A;
   output g41046_A1;
   output g41037_A2;
   output g41036_A2;
   output g41049_A;
   output g41037_A1;
   output g41067_A;
   output g41060_A;
   output g41029_A2;
   output g41054_B1;
   output g41075_A;
   output g41055_A2;
   output g41044_A3;
   output g41024_A2;
   output g41028_A3;
   output g41071_A1;
   output g41039_A3;
   output g41090_A;
   output g41086_A1;
   output g41066_A2;
   output g41092_B;
   output g41092_C1;
   output g41096_A;
   output g40966_A;
   output g41107_A1;
   output g41103_A;
   output g41119_A1;
   output g41100_B;
   output g41131_A;
   output g41122_B;
   output g41126_A;
   output g41126_B;
   output g41092_C2;
   output g41114_B;
   output g41096_B;
   output g41107_A2;
   output g41142_A;
   output g41073_A2;
   output g41138_B;
   output g40982_A2;
   output g41098_A2;
   output g41140_B;
   output g41140_A;
   output g41137_A;
   output g40966_C2;
   output g41183_A1;
   output g41073_A3;
   output g41123_A;

   // Internal wires
   wire bottom_n_200;
   wire bottom_n_201;
   wire bottom_n_203;
   wire bottom_n_212;
   wire bottom_n_219;
   wire bottom_n_220;
   wire bottom_n_221;
   wire bottom_n_231;
   wire bottom_n_268;
   wire bottom_n_269;
   wire bottom_n_270;
   wire bottom_n_271;
   wire bottom_n_272;
   wire bottom_n_273;
   wire bottom_n_274;
   wire bottom_n_275;
   wire bottom_n_276;
   wire bottom_n_277;
   wire bottom_n_278;
   wire bottom_n_279;
   wire bottom_n_280;
   wire bottom_n_281;
   wire bottom_n_282;
   wire bottom_n_283;
   wire bottom_n_284;
   wire bottom_n_285;
   wire bottom_n_286;
   wire bottom_n_287;
   wire bottom_n_288;
   wire bottom_n_289;
   wire bottom_n_290;
   wire bottom_n_291;
   wire bottom_n_292;
   wire bottom_n_293;
   wire bottom_n_294;
   wire bottom_n_295;
   wire bottom_n_296;
   wire bottom_n_297;
   wire bottom_n_298;
   wire bottom_n_299;
   wire bottom_n_300;
   wire bottom_n_301;
   wire bottom_n_302;

   NOR2_X1 g40963 (.A1(bottom_n_231),
	.A2(g41179_ZN),
	.ZN(G57));
   NAND2_X1 g40960 (.A1(bottom_n_220),
	.A2(bottom_n_219),
	.ZN(G51));
   NAND2_X1 g40962 (.A1(g40971_ZN),
	.A2(g40975_ZN),
	.ZN(G54));
   NAND2_X1 g40961 (.A1(g40970_ZN),
	.A2(bottom_n_221),
	.ZN(G66));
   NAND2_X1 g40958 (.A1(g40966_ZN),
	.A2(g40976_ZN),
	.ZN(G60));
   XNOR2_X1 g40968 (.A(g40981_ZN),
	.B(bottom_n_268),
	.ZN(bottom_n_231));
   XOR2_X1 g40964 (.A(bottom_n_212),
	.B(bottom_n_269),
	.Z(G72));
   OAI211_X1 g40967 (.A(bottom_n_270),
	.B(g40982_A2),
	.C1(g40980_ZN),
	.C2(g41186_ZN),
	.ZN(g40959_A1));
   NAND3_X1 g40978 (.A1(g40982_ZN),
	.A2(g41114_ZN),
	.A3(G217),
	.ZN(bottom_n_221));
   OAI211_X1 g40969 (.A(g41103_ZN),
	.B(g40982_A2),
	.C1(g40980_ZN),
	.C2(g41192_ZN),
	.ZN(bottom_n_220));
   NAND3_X1 g40974 (.A1(g40982_ZN),
	.A2(bottom_n_271),
	.A3(G210),
	.ZN(bottom_n_219));
   NAND2_X1 g40979 (.A1(g40965_B1),
	.A2(g41103_A),
	.ZN(g40965_A));
   OAI22_X1 g40972 (.A1(g40983_ZN),
	.A2(g41117_ZN),
	.B1(bottom_n_203),
	.B2(bottom_n_272),
	.ZN(bottom_n_212));
   NOR4_X1 g40990 (.A1(g40985_A1),
	.A2(g40985_A4),
	.A3(bottom_n_200),
	.A4(g41013_A),
	.ZN(g40973_A1));
   AOI22_X1 g40984 (.A1(g40993_ZN),
	.A2(bottom_n_201),
	.B1(G953),
	.B2(G224),
	.ZN(g40965_B1));
   AND2_X1 g40988 (.A1(bottom_n_203),
	.A2(g41190_ZN),
	.ZN(g40983_A));
   NAND2_X1 g40991 (.A1(g41006_ZN),
	.A2(g41002_ZN),
	.ZN(g40985_A1));
   NOR4_X1 g40992 (.A1(g41002_A),
	.A2(bottom_n_200),
	.A3(g41016_A),
	.A4(G953),
	.ZN(bottom_n_201));
   NOR3_X1 g40994 (.A1(g40985_A3),
	.A2(g41032_ZN),
	.A3(g41039_ZN),
	.ZN(bottom_n_203));
   OAI33_X1 g40987 (.A1(bottom_n_273),
	.A2(bottom_n_274),
	.A3(g41085_ZN),
	.B1(g41072_ZN),
	.B2(g41066_ZN),
	.B3(g41062_ZN),
	.ZN(g40986_A));
   AND4_X1 g40996 (.A1(bottom_n_275),
	.A2(bottom_n_276),
	.A3(bottom_n_277),
	.A4(g41032_A),
	.ZN(g40989_A1));
   INV_X1 g41003 (.A(g41006_ZN),
	.ZN(g40993_A1));
   NAND2_X1 g41005 (.A1(g41029_ZN),
	.A2(bottom_n_278),
	.ZN(g41002_A));
   XOR2_X1 g41000 (.A(g41028_ZN),
	.B(G107),
	.Z(G9));
   XOR2_X1 g41001 (.A(G128),
	.B(g41024_ZN),
	.Z(G30));
   XOR2_X1 g40997 (.A(G146),
	.B(bottom_n_279),
	.Z(G48));
   NAND2_X1 g41004 (.A1(bottom_n_275),
	.A2(bottom_n_277),
	.ZN(g40985_A3));
   NAND3_X1 g41008 (.A1(g40989_A3),
	.A2(bottom_n_276),
	.A3(g41032_A),
	.ZN(g40985_A2));
   OAI22_X1 g41009 (.A1(bottom_n_280),
	.A2(g41077_ZN),
	.B1(g41072_ZN),
	.B2(g41029_A2),
	.ZN(g40986_B1));
   XOR2_X1 g41019 (.A(G134),
	.B(bottom_n_281),
	.Z(G36));
   INV_X1 g41020 (.A(g40989_A2),
	.ZN(g40985_A4));
   XNOR2_X1 g41011 (.A(bottom_n_276),
	.B(G113),
	.ZN(G15));
   XOR2_X1 g41017 (.A(g41035_ZN),
	.B(G119),
	.Z(G21));
   INV_X1 g41027 (.A(g41028_ZN),
	.ZN(bottom_n_278));
   XNOR2_X1 g41010 (.A(g41036_ZN),
	.B(G125),
	.ZN(G27));
   XOR2_X1 g41015 (.A(G140),
	.B(g41037_ZN),
	.Z(G42));
   NOR3_X1 g41007 (.A1(g41037_A2),
	.A2(g41036_A2),
	.A3(bottom_n_282),
	.ZN(bottom_n_273));
   NOR2_X1 g41021 (.A1(g41016_A),
	.A2(g41035_ZN),
	.ZN(g40989_A2));
   NOR2_X1 g41022 (.A1(g41039_ZN),
	.A2(g41013_A),
	.ZN(g40989_A3));
   NOR2_X1 g41023 (.A1(g41024_A1),
	.A2(g41044_A3),
	.ZN(bottom_n_279));
   NOR3_X1 g41025 (.A1(g41029_A1),
	.A2(g41066_ZN),
	.A3(g41085_ZN),
	.ZN(g41006_A2));
   NOR3_X1 g41026 (.A1(g41029_A1),
	.A2(g41067_A),
	.A3(bottom_n_283),
	.ZN(g41006_A1));
   NAND3_X1 g41030 (.A1(g41054_ZN),
	.A2(g41037_A2),
	.A3(g41131_A),
	.ZN(bottom_n_275));
   OAI21_X1 g41031 (.A(g41037_A1),
	.B1(g41037_A2),
	.B2(g41036_A2),
	.ZN(bottom_n_277));
   NAND4_X1 g41038 (.A1(g41049_ZN),
	.A2(g41065_ZN),
	.A3(bottom_n_284),
	.A4(g41131_A),
	.ZN(g41032_A));
   NOR3_X1 g41045 (.A1(g41046_A1),
	.A2(g41066_ZN),
	.A3(g41024_A2),
	.ZN(bottom_n_281));
   AOI22_X1 g41048 (.A1(bottom_n_285),
	.A2(bottom_n_284),
	.B1(g41067_ZN),
	.B2(g41086_ZN),
	.ZN(bottom_n_280));
   NAND2_X1 g41033 (.A1(g41049_ZN),
	.A2(g41134_ZN),
	.ZN(g41029_A1));
   NAND2_X1 g41034 (.A1(g41049_ZN),
	.A2(g41065_ZN),
	.ZN(g41024_A1));
   INV_X1 g41040 (.A(bottom_n_200),
	.ZN(bottom_n_276));
   NOR3_X1 g41041 (.A1(g41055_ZN),
	.A2(g41066_ZN),
	.A3(bottom_n_283),
	.ZN(bottom_n_200));
   NOR3_X4 g41042 (.A1(g41055_ZN),
	.A2(g41066_ZN),
	.A3(g41028_A3),
	.ZN(g41013_A));
   NOR3_X1 g41043 (.A1(g41055_ZN),
	.A2(g41067_A),
	.A3(g41039_A3),
	.ZN(g41016_A));
   OAI22_X1 g41047 (.A1(g41062_ZN),
	.A2(g41090_A),
	.B1(g41064_ZN),
	.B2(g41077_ZN),
	.ZN(bottom_n_282));
   INV_X1 g41051 (.A(g41037_A2),
	.ZN(g41046_A1));
   INV_X1 g41058 (.A(bottom_n_285),
	.ZN(bottom_n_274));
   NOR2_X1 g41052 (.A1(g41060_ZN),
	.A2(g41077_ZN),
	.ZN(g41037_A2));
   NOR2_X1 g41053 (.A1(g41062_ZN),
	.A2(g41079_ZN),
	.ZN(g41036_A2));
   NOR2_X1 g41059 (.A1(g41067_A),
	.A2(g41160_ZN),
	.ZN(bottom_n_285));
   NAND2_X1 g41050 (.A1(g41060_A),
	.A2(g41055_A2),
	.ZN(g41049_A));
   NOR2_X1 g41057 (.A1(g41029_A2),
	.A2(g41044_A3),
	.ZN(g41037_A1));
   NAND2_X1 g41068 (.A1(g41075_ZN),
	.A2(g41066_A2),
	.ZN(g41067_A));
   OAI21_X1 g41061 (.A(g41070_ZN),
	.B1(g41073_ZN),
	.B2(G469),
	.ZN(g41060_A));
   OR2_X1 g41069 (.A1(g41075_A),
	.A2(g41066_A2),
	.ZN(g41029_A2));
   INV_X1 g41082 (.A(bottom_n_284),
	.ZN(g41054_B1));
   XOR2_X1 g41076 (.A(g41092_ZN),
	.B(G472),
	.Z(g41075_A));
   INV_X1 g41078 (.A(g41079_ZN),
	.ZN(g41055_A2));
   OR2_X1 g41080 (.A1(bottom_n_283),
	.A2(g41131_ZN),
	.ZN(g41044_A3));
   OR2_X1 g41081 (.A1(g41028_A3),
	.A2(g41131_ZN),
	.ZN(g41024_A2));
   NAND2_X1 g41083 (.A1(g41028_A3),
	.A2(bottom_n_283),
	.ZN(bottom_n_284));
   NAND2_X1 g41088 (.A1(g41086_A1),
	.A2(g41108_ZN),
	.ZN(bottom_n_283));
   OR2_X1 g41089 (.A1(g41086_A1),
	.A2(g41108_ZN),
	.ZN(g41028_A3));
   OAI211_X1 g41074 (.A(g41094_ZN),
	.B(g41073_A3),
	.C1(bottom_n_286),
	.C2(g41144_ZN),
	.ZN(g41071_A1));
   NAND2_X1 g41087 (.A1(g41086_A1),
	.A2(g41109_ZN),
	.ZN(g41039_A3));
   XNOR2_X1 g41101 (.A(g41092_C1),
	.B(g41092_C2),
	.ZN(bottom_n_268));
   OAI21_X1 g41091 (.A(g41096_ZN),
	.B1(g41103_ZN),
	.B2(bottom_n_287),
	.ZN(g41090_A));
   XNOR2_X1 g41097 (.A(bottom_n_288),
	.B(g40966_C2),
	.ZN(g41086_A1));
   NAND2_X1 g41105 (.A1(g41117_ZN),
	.A2(g41190_ZN),
	.ZN(bottom_n_272));
   AND2_X1 g41095 (.A1(g41098_ZN),
	.A2(g41107_ZN),
	.ZN(g41066_A2));
   INV_X1 g41102 (.A(g41103_ZN),
	.ZN(bottom_n_271));
   OAI33_X1 g41110 (.A1(g41123_A),
	.A2(bottom_n_289),
	.A3(g41092_C2),
	.B1(g41123_ZN),
	.B2(bottom_n_290),
	.B3(g41092_C2),
	.ZN(g41092_B));
   OAI22_X1 g41116 (.A1(g41123_A),
	.A2(bottom_n_290),
	.B1(g41123_ZN),
	.B2(bottom_n_289),
	.ZN(g41092_C1));
   AOI22_X1 g41118 (.A1(g41123_ZN),
	.A2(g41137_ZN),
	.B1(g41123_A),
	.B2(g41100_B),
	.ZN(bottom_n_286));
   NOR2_X1 g41104 (.A1(g41112_ZN),
	.A2(G902),
	.ZN(bottom_n_288));
   NAND3_X1 g41106 (.A1(g41103_A),
	.A2(bottom_n_291),
	.A3(g41181_ZN),
	.ZN(g41096_A));
   INV_X1 g41111 (.A(g41112_ZN),
	.ZN(g40966_A));
   INV_X1 g41113 (.A(g41114_ZN),
	.ZN(g41107_A1));
   XNOR2_X1 g41115 (.A(g41129_ZN),
	.B(bottom_n_289),
	.ZN(g41103_A));
   INV_X1 g41127 (.A(g41119_A1),
	.ZN(bottom_n_291));
   INV_X1 g41121 (.A(g41122_ZN),
	.ZN(bottom_n_270));
   XNOR2_X1 g41128 (.A(bottom_n_292),
	.B(bottom_n_293),
	.ZN(g41119_A1));
   NAND2_X1 g41141 (.A1(bottom_n_294),
	.A2(bottom_n_295),
	.ZN(bottom_n_293));
   INV_X1 g41132 (.A(bottom_n_289),
	.ZN(bottom_n_290));
   INV_X1 g41133 (.A(g41137_ZN),
	.ZN(g41100_B));
   OAI21_X1 g41135 (.A(g41160_ZN),
	.B1(g41159_ZN),
	.B2(G900),
	.ZN(g41131_A));
   XNOR2_X1 g41136 (.A(bottom_n_296),
	.B(G119),
	.ZN(bottom_n_289));
   XNOR2_X1 g41139 (.A(bottom_n_297),
	.B(bottom_n_298),
	.ZN(g41122_B));
   XNOR2_X1 g41143 (.A(g41175_Z),
	.B(G146),
	.ZN(g41126_A));
   XNOR2_X1 g41145 (.A(g41169_Z),
	.B(G110),
	.ZN(g41126_B));
   XNOR2_X1 g41146 (.A(g41162_ZN),
	.B(G101),
	.ZN(g41092_C2));
   XOR2_X1 g41148 (.A(g41157_ZN),
	.B(G137),
	.Z(g41114_B));
   NAND2_X1 g41150 (.A1(g41138_B),
	.A2(G146),
	.ZN(bottom_n_294));
   OAI21_X1 g41151 (.A(g41181_ZN),
	.B1(g41183_ZN),
	.B2(G902),
	.ZN(g41096_B));
   XOR2_X1 g41152 (.A(g41176_ZN),
	.B(G125),
	.Z(bottom_n_292));
   NOR2_X1 g41153 (.A1(g41098_A2),
	.A2(G902),
	.ZN(g41107_A2));
   NAND2_X1 g41149 (.A1(g41165_ZN),
	.A2(bottom_n_299),
	.ZN(bottom_n_295));
   NAND3_X1 g41161 (.A1(g41190_ZN),
	.A2(g41183_A1),
	.A3(G214),
	.ZN(g41142_A));
   OAI21_X1 g41156 (.A(G221),
	.B1(bottom_n_300),
	.B2(G902),
	.ZN(g41073_A2));
   INV_X1 g41182 (.A(g41183_ZN),
	.ZN(bottom_n_287));
   INV_X1 g41164 (.A(g41165_ZN),
	.ZN(g41138_B));
   INV_X1 g41178 (.A(g41179_ZN),
	.ZN(g40982_A2));
   NOR2_X1 g41184 (.A1(g41187_ZN),
	.A2(G234),
	.ZN(g41098_A2));
   AOI21_X1 g41154 (.A(g41190_ZN),
	.B1(G227),
	.B2(G900),
	.ZN(bottom_n_269));
   XNOR2_X1 g41163 (.A(G134),
	.B(G131),
	.ZN(bottom_n_301));
   XOR2_X1 g41166 (.A(G116),
	.B(G107),
	.Z(bottom_n_297));
   XNOR2_X1 g41168 (.A(G113),
	.B(G104),
	.ZN(g41140_B));
   XNOR2_X1 g41172 (.A(G122),
	.B(G134),
	.ZN(bottom_n_298));
   XNOR2_X1 g41173 (.A(G122),
	.B(G131),
	.ZN(g41140_A));
   XOR2_X1 g41167 (.A(G107),
	.B(G104),
	.Z(g41137_A));
   XNOR2_X1 g41170 (.A(G116),
	.B(G113),
	.ZN(bottom_n_296));
   INV_X1 g41193 (.A(G146),
	.ZN(bottom_n_299));
   INV_X1 g41194 (.A(G475),
	.ZN(g40966_C2));
   INV_X1 g41189 (.A(G237),
	.ZN(g41183_A1));
   INV_X1 g41185 (.A(G234),
	.ZN(bottom_n_300));
   INV_X1 g41188 (.A(G902),
	.ZN(g41073_A3));
   XOR2_X1 g2 (.A(bottom_n_301),
	.B(G137),
	.Z(bottom_n_302));
   XNOR2_X1 g41196 (.A(bottom_n_293),
	.B(bottom_n_302),
	.ZN(g41123_A));
endmodule

