/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID aduae260-lap)
#  Generated on:      Tue Sep 25 17:17:58 2018
#  Design:            c432
#  Command:           saveNetlist -module top outputs/top_j.v
###############################################################
*/
module top (
	G1GAT, 
	G4GAT, 
	G8GAT, 
	G14GAT, 
	G17GAT, 
	G24GAT, 
	G30GAT, 
	G34GAT, 
	G37GAT, 
	G40GAT, 
	G43GAT, 
	G47GAT, 
	G50GAT, 
	G53GAT, 
	G56GAT, 
	G60GAT, 
	G63GAT, 
	G66GAT, 
	G69GAT, 
	G73GAT, 
	G79GAT, 
	G82GAT, 
	G86GAT, 
	G89GAT, 
	G92GAT, 
	G95GAT, 
	G102GAT, 
	G105GAT, 
	G108GAT, 
	G112GAT, 
	bottom_g36995_B2, 
	bottom_g36996_A1, 
	bottom_g37005_A2, 
	bottom_g36997_A, 
	bottom_g37001_A1, 
	bottom_g37002_A2, 
	bottom_g37000_A1, 
	bottom_g37013_A, 
	bottom_G370GAT, 
	bottom_g37011_A, 
	bottom_G329GAT, 
	bottom_g37012_A, 
	bottom_g37019_A, 
	bottom_g37027_A1, 
	bottom_g37071_A1, 
	bottom_g37027_A3, 
	bottom_g37029_A, 
	bottom_g37031_A2, 
	bottom_g37031_B2, 
	bottom_g37044_A3, 
	bottom_g37028_A, 
	bottom_g37033_A2, 
	bottom_g37033_C2, 
	bottom_g37033_B2, 
	bottom_g37041_A1, 
	bottom_g37037_A, 
	bottom_g37041_A2, 
	bottom_g37041_A3, 
	bottom_g37044_A1, 
	bottom_g37044_A4, 
	bottom_g37051_A1, 
	bottom_g37065_A1, 
	bottom_g37068_A1, 
	bottom_g37071_A2, 
	bottom_g37080_A, 
	bottom_g37084_B, 
	bottom_g37084_C1, 
	bottom_g37085_B1, 
	bottom_g37086_A1, 
	bottom_g37090_A1, 
	bottom_g37092_A1, 
	G223GAT, 
	G421GAT, 
	G430GAT, 
	G431GAT, 
	G432GAT, 
	bottom_g37004_ZN, 
	bottom_g37013_ZN, 
	bottom_g37010_ZN, 
	bottom_g37011_ZN, 
	bottom_g37017_ZN, 
	bottom_g37018_ZN, 
	bottom_g37027_ZN, 
	bottom_g37031_ZN, 
	bottom_g37026_ZN, 
	bottom_g37028_ZN, 
	bottom_g37033_ZN, 
	bottom_g37041_ZN, 
	bottom_g37040_ZN, 
	bottom_g37044_ZN, 
	bottom_g37050_ZN, 
	bottom_g37051_ZN, 
	bottom_g37053_ZN, 
	bottom_g37060_ZN, 
	bottom_g37068_ZN, 
	bottom_g37071_ZN, 
	bottom_g37080_ZN, 
	bottom_g37074_ZN, 
	bottom_g37075_ZN, 
	bottom_g37078_ZN, 
	bottom_g37083_ZN, 
	bottom_g37085_ZN, 
	bottom_g37090_ZN, 
	bottom_g37095_ZN, 
	bottom_g37093_ZN, 
	bottom_g37113_ZN, 
	bottom_g37097_ZN, 
	bottom_g37102_ZN, 
	bottom_g37099_ZN);
   input G1GAT;
   input G4GAT;
   input G8GAT;
   input G14GAT;
   input G17GAT;
   input G24GAT;
   input G30GAT;
   input G34GAT;
   input G37GAT;
   input G40GAT;
   input G43GAT;
   input G47GAT;
   input G50GAT;
   input G53GAT;
   input G56GAT;
   input G60GAT;
   input G63GAT;
   input G66GAT;
   input G69GAT;
   input G73GAT;
   input G79GAT;
   input G82GAT;
   input G86GAT;
   input G89GAT;
   input G92GAT;
   input G95GAT;
   input G102GAT;
   input G105GAT;
   input G108GAT;
   input G112GAT;
   input bottom_g36995_B2;
   input bottom_g36996_A1;
   input bottom_g37005_A2;
   input bottom_g36997_A;
   input bottom_g37001_A1;
   input bottom_g37002_A2;
   input bottom_g37000_A1;
   input bottom_g37013_A;
   input bottom_G370GAT;
   input bottom_g37011_A;
   input bottom_G329GAT;
   input bottom_g37012_A;
   input bottom_g37019_A;
   input bottom_g37027_A1;
   input bottom_g37071_A1;
   input bottom_g37027_A3;
   input bottom_g37029_A;
   input bottom_g37031_A2;
   input bottom_g37031_B2;
   input bottom_g37044_A3;
   input bottom_g37028_A;
   input bottom_g37033_A2;
   input bottom_g37033_C2;
   input bottom_g37033_B2;
   input bottom_g37041_A1;
   input bottom_g37037_A;
   input bottom_g37041_A2;
   input bottom_g37041_A3;
   input bottom_g37044_A1;
   input bottom_g37044_A4;
   input bottom_g37051_A1;
   input bottom_g37065_A1;
   input bottom_g37068_A1;
   input bottom_g37071_A2;
   input bottom_g37080_A;
   input bottom_g37084_B;
   input bottom_g37084_C1;
   input bottom_g37085_B1;
   input bottom_g37086_A1;
   input bottom_g37090_A1;
   input bottom_g37092_A1;
   output G223GAT;
   output G421GAT;
   output G430GAT;
   output G431GAT;
   output G432GAT;
   output bottom_g37004_ZN;
   output bottom_g37013_ZN;
   output bottom_g37010_ZN;
   output bottom_g37011_ZN;
   output bottom_g37017_ZN;
   output bottom_g37018_ZN;
   output bottom_g37027_ZN;
   output bottom_g37031_ZN;
   output bottom_g37026_ZN;
   output bottom_g37028_ZN;
   output bottom_g37033_ZN;
   output bottom_g37041_ZN;
   output bottom_g37040_ZN;
   output bottom_g37044_ZN;
   output bottom_g37050_ZN;
   output bottom_g37051_ZN;
   output bottom_g37053_ZN;
   output bottom_g37060_ZN;
   output bottom_g37068_ZN;
   output bottom_g37071_ZN;
   output bottom_g37080_ZN;
   output bottom_g37074_ZN;
   output bottom_g37075_ZN;
   output bottom_g37078_ZN;
   output bottom_g37083_ZN;
   output bottom_g37085_ZN;
   output bottom_g37090_ZN;
   output bottom_g37095_ZN;
   output bottom_g37093_ZN;
   output bottom_g37113_ZN;
   output bottom_g37097_ZN;
   output bottom_g37102_ZN;
   output bottom_g37099_ZN;

   // Internal wires
   wire top_n_112;
   wire top_n_156;
   wire top_n_157;
   wire top_n_158;
   wire top_n_159;
   wire top_n_160;
   wire top_n_161;
   wire top_n_162;
   wire top_n_163;
   wire top_n_164;
   wire top_n_165;
   wire top_n_166;
   wire top_n_167;
   wire top_n_168;
   wire top_n_169;
   wire top_n_170;
   wire top_n_171;
   wire top_n_172;
   wire top_n_173;
   wire top_n_174;
   wire top_n_175;
   wire top_n_176;

   AOI21_X1 g36995 (.A(top_n_156),
	.B1(top_n_112),
	.B2(bottom_g36995_B2),
	.ZN(G421GAT));
   OR4_X1 g36996 (.A1(bottom_g36996_A1),
	.A2(top_n_157),
	.A3(top_n_158),
	.A4(bottom_g37005_A2),
	.ZN(G432GAT));
   INV_X1 g36997 (.A(bottom_g36997_A),
	.ZN(G431GAT));
   NOR3_X1 g37001 (.A1(bottom_g37001_A1),
	.A2(bottom_g37017_ZN),
	.A3(bottom_g37010_ZN),
	.ZN(top_n_112));
   NOR3_X1 g37002 (.A1(bottom_g37010_ZN),
	.A2(bottom_g37002_A2),
	.A3(bottom_g37011_ZN),
	.ZN(top_n_157));
   NAND2_X1 g37000 (.A1(bottom_g37000_A1),
	.A2(top_n_159),
	.ZN(G430GAT));
   INV_X1 g37004 (.A(top_n_159),
	.ZN(bottom_g37004_ZN));
   OAI33_X1 g37008 (.A1(top_n_160),
	.A2(top_n_161),
	.A3(top_n_162),
	.B1(top_n_162),
	.B2(top_n_163),
	.B3(G53GAT),
	.ZN(top_n_158));
   NOR2_X1 g37005 (.A1(bottom_g37010_ZN),
	.A2(bottom_g37005_A2),
	.ZN(top_n_159));
   INV_X1 g37013 (.A(bottom_g37013_A),
	.ZN(bottom_g37013_ZN));
   AOI21_X1 g37010 (.A(top_n_164),
	.B1(bottom_G370GAT),
	.B2(G40GAT),
	.ZN(bottom_g37010_ZN));
   AOI221_X1 g37011 (.A(bottom_g37011_A),
	.B1(bottom_G329GAT),
	.B2(G60GAT),
	.C1(bottom_G370GAT),
	.C2(G66GAT),
	.ZN(bottom_g37011_ZN));
   AOI221_X1 g37012 (.A(bottom_g37012_A),
	.B1(bottom_G329GAT),
	.B2(G8GAT),
	.C1(bottom_G370GAT),
	.C2(G14GAT),
	.ZN(top_n_156));
   AOI221_X1 g37017 (.A(top_n_165),
	.B1(bottom_G329GAT),
	.B2(G73GAT),
	.C1(bottom_G370GAT),
	.C2(G79GAT),
	.ZN(bottom_g37017_ZN));
   INV_X1 g37019 (.A(bottom_g37019_A),
	.ZN(top_n_160));
   NAND2_X1 g37018 (.A1(bottom_G370GAT),
	.A2(G92GAT),
	.ZN(bottom_g37018_ZN));
   NAND4_X1 g37027 (.A1(bottom_g37027_A1),
	.A2(bottom_g37071_A1),
	.A3(bottom_g37027_A3),
	.A4(G82GAT),
	.ZN(bottom_g37027_ZN));
   INV_X1 g37023 (.A(top_n_161),
	.ZN(top_n_164));
   INV_X1 g37029 (.A(bottom_g37029_A),
	.ZN(top_n_162));
   OAI22_X1 g37031 (.A1(top_n_166),
	.A2(bottom_g37031_A2),
	.B1(bottom_g37050_ZN),
	.B2(bottom_g37031_B2),
	.ZN(bottom_g37031_ZN));
   AOI21_X1 g37024 (.A(bottom_g37053_ZN),
	.B1(bottom_G329GAT),
	.B2(G34GAT),
	.ZN(top_n_161));
   OAI211_X1 g37026 (.A(bottom_G329GAT),
	.B(top_n_167),
	.C1(top_n_168),
	.C2(bottom_g37044_A3),
	.ZN(bottom_g37026_ZN));
   AOI21_X1 g37028 (.A(bottom_g37028_A),
	.B1(bottom_G329GAT),
	.B2(G86GAT),
	.ZN(bottom_g37028_ZN));
   OAI222_X1 g37033 (.A1(bottom_g37044_ZN),
	.A2(bottom_g37033_A2),
	.B1(bottom_g37033_C2),
	.B2(bottom_g37033_B2),
	.C1(bottom_g37041_A1),
	.C2(bottom_g37033_C2),
	.ZN(bottom_g37033_ZN));
   INV_X1 g37034 (.A(bottom_G329GAT),
	.ZN(top_n_166));
   INV_X1 g37037 (.A(bottom_g37037_A),
	.ZN(top_n_167));
   NOR3_X1 g37041 (.A1(bottom_g37041_A1),
	.A2(bottom_g37041_A2),
	.A3(bottom_g37041_A3),
	.ZN(bottom_g37041_ZN));
   OAI21_X1 g37040 (.A(top_n_168),
	.B1(top_n_165),
	.B2(G79GAT),
	.ZN(bottom_g37040_ZN));
   AND4_X1 g37044 (.A1(bottom_g37044_A1),
	.A2(bottom_g37071_ZN),
	.A3(bottom_g37044_A3),
	.A4(bottom_g37044_A4),
	.ZN(bottom_g37044_ZN));
   NOR2_X1 g37050 (.A1(bottom_g37060_ZN),
	.A2(G105GAT),
	.ZN(bottom_g37050_ZN));
   OR2_X1 g37051 (.A1(bottom_g37051_A1),
	.A2(bottom_g37068_ZN),
	.ZN(bottom_g37051_ZN));
   NAND2_X1 g37053 (.A1(bottom_g37075_ZN),
	.A2(G30GAT),
	.ZN(bottom_g37053_ZN));
   NAND2_X1 g37059 (.A1(bottom_g37074_ZN),
	.A2(G69GAT),
	.ZN(top_n_165));
   NAND2_X1 g37060 (.A1(top_n_169),
	.A2(G95GAT),
	.ZN(bottom_g37060_ZN));
   NAND3_X1 g37065 (.A1(bottom_g37065_A1),
	.A2(top_n_170),
	.A3(G56GAT),
	.ZN(top_n_168));
   NAND3_X1 g37068 (.A1(bottom_g37068_A1),
	.A2(top_n_171),
	.A3(G108GAT),
	.ZN(bottom_g37068_ZN));
   NAND3_X1 g37071 (.A1(bottom_g37071_A1),
	.A2(bottom_g37071_A2),
	.A3(G82GAT),
	.ZN(bottom_g37071_ZN));
   INV_X1 g37080 (.A(bottom_g37080_A),
	.ZN(bottom_g37080_ZN));
   NAND2_X1 g37074 (.A1(G223GAT),
	.A2(G63GAT),
	.ZN(bottom_g37074_ZN));
   NAND2_X1 g37075 (.A1(G223GAT),
	.A2(G24GAT),
	.ZN(bottom_g37075_ZN));
   NAND2_X1 g37077 (.A1(G223GAT),
	.A2(G89GAT),
	.ZN(top_n_169));
   NAND2_X1 g37078 (.A1(G223GAT),
	.A2(G1GAT),
	.ZN(bottom_g37078_ZN));
   INV_X1 g37083 (.A(G223GAT),
	.ZN(bottom_g37083_ZN));
   OAI211_X2 g37084 (.A(top_n_172),
	.B(bottom_g37084_B),
	.C1(bottom_g37084_C1),
	.C2(G89GAT),
	.ZN(G223GAT));
   AOI22_X1 g37085 (.A1(top_n_173),
	.A2(G89GAT),
	.B1(bottom_g37085_B1),
	.B2(G37GAT),
	.ZN(bottom_g37085_ZN));
   NOR2_X1 g37086 (.A1(bottom_g37086_A1),
	.A2(top_n_174),
	.ZN(top_n_172));
   OR2_X1 g37088 (.A1(bottom_g37093_ZN),
	.A2(G37GAT),
	.ZN(top_n_173));
   AOI22_X1 g37090 (.A1(bottom_g37090_A1),
	.A2(G17GAT),
	.B1(top_n_175),
	.B2(G4GAT),
	.ZN(bottom_g37090_ZN));
   OAI22_X1 g37092 (.A1(bottom_g37092_A1),
	.A2(G63GAT),
	.B1(top_n_176),
	.B2(G50GAT),
	.ZN(top_n_174));
   OR2_X1 g37095 (.A1(bottom_g37097_ZN),
	.A2(G53GAT),
	.ZN(bottom_g37095_ZN));
   OR2_X1 g37093 (.A1(bottom_g37097_ZN),
	.A2(G47GAT),
	.ZN(bottom_g37093_ZN));
   INV_X1 g37113 (.A(G102GAT),
	.ZN(bottom_g37113_ZN));
   INV_X1 g37106 (.A(G112GAT),
	.ZN(top_n_171));
   INV_X1 g37097 (.A(G43GAT),
	.ZN(bottom_g37097_ZN));
   INV_X1 g37100 (.A(G1GAT),
	.ZN(top_n_175));
   INV_X1 g37098 (.A(G66GAT),
	.ZN(top_n_170));
   INV_X1 g37102 (.A(G34GAT),
	.ZN(bottom_g37102_ZN));
   INV_X1 g37114 (.A(G56GAT),
	.ZN(top_n_176));
   INV_X1 g37109 (.A(G40GAT),
	.ZN(top_n_163));
   INV_X1 g37099 (.A(G60GAT),
	.ZN(bottom_g37099_ZN));
endmodule

