/*
###############################################################
#  Generated by:      Cadence Innovus 17.12-s095_1
#  OS:                Linux x86_64(Host ID aduae260-lap)
#  Generated on:      Fri Mar 16 12:43:28 2018
#  Design:            c432
#  Command:           saveNetlist -module bottom outputs/bottom.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 17.20-p003_1
// Generated on: Mar 16 2018 12:43:22 +04 (Mar 16 2018 08:43:22 UTC)
// Verification Directory fv/c432 
module bottom (
	G4GAT, 
	G8GAT, 
	G11GAT, 
	G14GAT, 
	G17GAT, 
	G21GAT, 
	G24GAT, 
	G27GAT, 
	G30GAT, 
	G37GAT, 
	G40GAT, 
	G43GAT, 
	G47GAT, 
	G50GAT, 
	G53GAT, 
	G56GAT, 
	G69GAT, 
	G73GAT, 
	G76GAT, 
	G79GAT, 
	G82GAT, 
	G86GAT, 
	G92GAT, 
	G95GAT, 
	G99GAT, 
	G102GAT, 
	G105GAT, 
	G108GAT, 
	G115GAT, 
	g37004_ZN, 
	g37017_ZN, 
	g37011_ZN, 
	g37018_ZN, 
	g37028_ZN, 
	g37060_ZN, 
	g37031_ZN, 
	g37027_ZN, 
	g37026_ZN, 
	g37040_ZN, 
	g37033_ZN, 
	g37041_ZN, 
	g37071_ZN, 
	g37051_ZN, 
	g37068_ZN, 
	g37044_ZN, 
	g37050_ZN, 
	g37080_ZN, 
	g37095_ZN, 
	g37053_ZN, 
	g37093_ZN, 
	g37078_ZN, 
	g37074_ZN, 
	g37075_ZN, 
	g37102_ZN, 
	g37099_ZN, 
	g37083_ZN, 
	g37085_ZN, 
	g37084_ZN, 
	g37090_ZN, 
	g37097_ZN, 
	g37113_ZN, 
	g37010_ZN, 
	g37013_ZN, 
	G329GAT, 
	G370GAT, 
	g36997_A, 
	g36995_B2, 
	g37001_A1, 
	g37000_A1, 
	g37002_A2, 
	g37013_A, 
	g37005_A2, 
	g37019_A, 
	g37029_A, 
	g37027_A1, 
	g37031_A2, 
	g37037_A, 
	g37033_B2, 
	g37041_A1, 
	g37033_A2, 
	g37033_C2, 
	g37031_B2, 
	g37041_A2, 
	g37012_A, 
	g37011_A, 
	g37028_A, 
	g37044_A1, 
	g37051_A1, 
	g37041_A3, 
	g37044_A3, 
	g37044_A4, 
	g37071_A1, 
	g37080_A, 
	g37065_A1, 
	g37068_A1, 
	g37086_A1, 
	g37084_B, 
	g37085_B1, 
	g37092_A1, 
	g37071_A2, 
	g37084_C1, 
	g37027_A3, 
	g37090_A1, 
	g36996_A1);
   input G4GAT;
   input G8GAT;
   input G11GAT;
   input G14GAT;
   input G17GAT;
   input G21GAT;
   input G24GAT;
   input G27GAT;
   input G30GAT;
   input G37GAT;
   input G40GAT;
   input G43GAT;
   input G47GAT;
   input G50GAT;
   input G53GAT;
   input G56GAT;
   input G69GAT;
   input G73GAT;
   input G76GAT;
   input G79GAT;
   input G82GAT;
   input G86GAT;
   input G92GAT;
   input G95GAT;
   input G99GAT;
   input G102GAT;
   input G105GAT;
   input G108GAT;
   input G115GAT;
   input g37004_ZN;
   input g37017_ZN;
   input g37011_ZN;
   input g37018_ZN;
   input g37028_ZN;
   input g37060_ZN;
   input g37031_ZN;
   input g37027_ZN;
   input g37026_ZN;
   input g37040_ZN;
   input g37033_ZN;
   input g37041_ZN;
   input g37071_ZN;
   input g37051_ZN;
   input g37068_ZN;
   input g37044_ZN;
   input g37050_ZN;
   input g37080_ZN;
   input g37095_ZN;
   input g37053_ZN;
   input g37093_ZN;
   input g37078_ZN;
   input g37074_ZN;
   input g37075_ZN;
   input g37102_ZN;
   input g37099_ZN;
   input g37083_ZN;
   input g37085_ZN;
   input g37084_ZN;
   input g37090_ZN;
   input g37097_ZN;
   input g37113_ZN;
   input g37010_ZN;
   input g37013_ZN;
   output G329GAT;
   output G370GAT;
   output g36997_A;
   output g36995_B2;
   output g37001_A1;
   output g37000_A1;
   output g37002_A2;
   output g37013_A;
   output g37005_A2;
   output g37019_A;
   output g37029_A;
   output g37027_A1;
   output g37031_A2;
   output g37037_A;
   output g37033_B2;
   output g37041_A1;
   output g37033_A2;
   output g37033_C2;
   output g37031_B2;
   output g37041_A2;
   output g37012_A;
   output g37011_A;
   output g37028_A;
   output g37044_A1;
   output g37051_A1;
   output g37041_A3;
   output g37044_A3;
   output g37044_A4;
   output g37071_A1;
   output g37080_A;
   output g37065_A1;
   output g37068_A1;
   output g37086_A1;
   output g37084_B;
   output g37085_B1;
   output g37092_A1;
   output g37071_A2;
   output g37084_C1;
   output g37027_A3;
   output g37090_A1;
   output g36996_A1;

   // Internal wires
   wire n_109;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;

   AOI221_X1 g36998 (.A(g37004_ZN),
	.B1(g37000_A1),
	.B2(n_109),
	.C1(g37000_A1),
	.C2(g37017_ZN),
	.ZN(g36997_A));
   NOR4_X1 g37003 (.A1(g37013_A),
	.A2(n_109),
	.A3(g37005_A2),
	.A4(G108GAT),
	.ZN(g36995_B2));
   INV_X1 g37006 (.A(g37000_A1),
	.ZN(g37001_A1));
   AOI21_X1 g37007 (.A(g37011_ZN),
	.B1(g37019_A),
	.B2(g37029_A),
	.ZN(g37000_A1));
   AND2_X1 g37009 (.A1(g37018_ZN),
	.A2(g37028_ZN),
	.ZN(n_109));
   INV_X1 g37016 (.A(g37017_ZN),
	.ZN(g37002_A2));
   AOI221_X1 g37014 (.A(g37060_ZN),
	.B1(G329GAT),
	.B2(G99GAT),
	.C1(G370GAT),
	.C2(G105GAT),
	.ZN(g37013_A));
   AOI221_X1 g37015 (.A(n_156),
	.B1(G329GAT),
	.B2(G21GAT),
	.C1(G370GAT),
	.C2(G27GAT),
	.ZN(g37005_A2));
   NAND2_X1 g37020 (.A1(G370GAT),
	.A2(G53GAT),
	.ZN(g37019_A));
   NAND4_X1 g37021 (.A1(g37031_ZN),
	.A2(g37027_ZN),
	.A3(n_157),
	.A4(n_158),
	.ZN(G370GAT));
   OAI21_X1 g37022 (.A(g37026_ZN),
	.B1(g37040_ZN),
	.B2(n_159),
	.ZN(n_157));
   OR3_X1 g37025 (.A1(g37033_ZN),
	.A2(g37041_ZN),
	.A3(n_160),
	.ZN(n_158));
   AOI21_X1 g37030 (.A(n_161),
	.B1(G329GAT),
	.B2(G47GAT),
	.ZN(g37029_A));
   NAND2_X1 g37032 (.A1(G329GAT),
	.A2(g37071_ZN),
	.ZN(g37027_A1));
   AOI22_X1 g37036 (.A1(g37051_ZN),
	.A2(g37085_B1),
	.B1(n_162),
	.B2(g37068_ZN),
	.ZN(g37031_A2));
   NAND2_X1 g37035 (.A1(g37044_ZN),
	.A2(n_163),
	.ZN(G329GAT));
   OAI221_X1 g37038 (.A(n_164),
	.B1(n_165),
	.B2(G27GAT),
	.C1(g37044_A1),
	.C2(G79GAT),
	.ZN(g37037_A));
   AOI21_X1 g37039 (.A(g37033_A2),
	.B1(g37068_ZN),
	.B2(n_165),
	.ZN(n_160));
   NAND2_X1 g37048 (.A1(g37041_A2),
	.A2(g37041_A3),
	.ZN(g37033_B2));
   INV_X1 g37049 (.A(g37050_ZN),
	.ZN(n_162));
   OAI22_X1 g37042 (.A1(n_156),
	.A2(G27GAT),
	.B1(g37080_ZN),
	.B2(g37095_ZN),
	.ZN(n_159));
   AND4_X1 g37043 (.A1(g37068_ZN),
	.A2(n_166),
	.A3(g37041_A3),
	.A4(n_165),
	.ZN(n_163));
   NOR2_X1 g37045 (.A1(g37053_ZN),
	.A2(G40GAT),
	.ZN(g37041_A1));
   NAND2_X1 g37046 (.A1(n_166),
	.A2(g37041_A3),
	.ZN(g37033_A2));
   NOR2_X1 g37047 (.A1(g37012_A),
	.A2(G14GAT),
	.ZN(g37033_C2));
   OR3_X1 g37052 (.A1(g37080_ZN),
	.A2(g37095_ZN),
	.A3(g37093_ZN),
	.ZN(n_164));
   INV_X1 g37062 (.A(g37051_A1),
	.ZN(g37031_B2));
   INV_X1 g37063 (.A(n_166),
	.ZN(g37041_A2));
   NAND2_X1 g37054 (.A1(g37078_ZN),
	.A2(G4GAT),
	.ZN(g37012_A));
   NAND2_X1 g37055 (.A1(g37065_A1),
	.A2(G56GAT),
	.ZN(g37011_A));
   NAND2_X1 g37056 (.A1(g37071_A1),
	.A2(G82GAT),
	.ZN(g37028_A));
   NAND2_X1 g37057 (.A1(g37080_A),
	.A2(G43GAT),
	.ZN(n_161));
   NAND2_X1 g37058 (.A1(n_167),
	.A2(G17GAT),
	.ZN(n_156));
   NAND3_X1 g37061 (.A1(g37074_ZN),
	.A2(n_168),
	.A3(G69GAT),
	.ZN(g37044_A1));
   NAND3_X1 g37064 (.A1(n_167),
	.A2(n_169),
	.A3(G17GAT),
	.ZN(n_165));
   NAND3_X1 g37066 (.A1(g37068_A1),
	.A2(n_170),
	.A3(G108GAT),
	.ZN(g37051_A1));
   NAND3_X1 g37067 (.A1(g37075_ZN),
	.A2(g37102_ZN),
	.A3(G30GAT),
	.ZN(g37041_A3));
   NAND3_X1 g37069 (.A1(g37078_ZN),
	.A2(n_171),
	.A3(G4GAT),
	.ZN(n_166));
   NAND3_X1 g37070 (.A1(g37065_A1),
	.A2(g37099_ZN),
	.A3(G56GAT),
	.ZN(g37044_A3));
   OAI21_X1 g37072 (.A(n_172),
	.B1(g37083_ZN),
	.B2(g37085_ZN),
	.ZN(g37044_A4));
   NAND2_X1 g37073 (.A1(g37084_ZN),
	.A2(G76GAT),
	.ZN(g37071_A1));
   NAND2_X1 g37076 (.A1(g37084_ZN),
	.A2(G11GAT),
	.ZN(n_167));
   NAND2_X1 g37081 (.A1(g37084_ZN),
	.A2(G37GAT),
	.ZN(g37080_A));
   NAND2_X1 g37082 (.A1(g37084_ZN),
	.A2(G50GAT),
	.ZN(g37065_A1));
   NAND2_X1 g37079 (.A1(g37084_ZN),
	.A2(G102GAT),
	.ZN(g37068_A1));
   OAI221_X1 g37087 (.A(g37090_ZN),
	.B1(g37097_ZN),
	.B2(G37GAT),
	.C1(n_173),
	.C2(G24GAT),
	.ZN(g37086_A1));
   NAND2_X1 g37089 (.A1(g37093_ZN),
	.A2(g37085_B1),
	.ZN(n_172));
   AOI22_X1 g37091 (.A1(g37113_ZN),
	.A2(G108GAT),
	.B1(n_174),
	.B2(G82GAT),
	.ZN(g37084_B));
   OR2_X1 g37094 (.A1(g37084_C1),
	.A2(G99GAT),
	.ZN(g37085_B1));
   INV_X1 g37112 (.A(G115GAT),
	.ZN(n_170));
   INV_X1 g37108 (.A(G8GAT),
	.ZN(n_171));
   INV_X1 g37111 (.A(G69GAT),
	.ZN(g37092_A1));
   INV_X1 g37115 (.A(G73GAT),
	.ZN(n_168));
   INV_X1 g37107 (.A(G30GAT),
	.ZN(n_173));
   INV_X1 g37096 (.A(G21GAT),
	.ZN(n_169));
   INV_X1 g37110 (.A(G86GAT),
	.ZN(g37071_A2));
   INV_X1 g37103 (.A(G95GAT),
	.ZN(g37084_C1));
   INV_X1 g37104 (.A(G76GAT),
	.ZN(n_174));
   INV_X1 g37101 (.A(G92GAT),
	.ZN(g37027_A3));
   INV_X1 g37105 (.A(G11GAT),
	.ZN(g37090_A1));
   AOI211_X1 g2 (.A(g37010_ZN),
	.B(g37013_ZN),
	.C1(g37018_ZN),
	.C2(g37028_ZN),
	.ZN(g36996_A1));
endmodule

