/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID aduae260-lap)
#  Generated on:      Fri Oct  5 14:06:56 2018
#  Design:            b18
#  Command:           saveNetlist -module b18_old outputs/wrapper_j.v
###############################################################
*/
