/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID aduae260-lap)
#  Generated on:      Wed Sep 26 11:40:53 2018
#  Design:            c880
#  Command:           saveNetlist -module bottom outputs/bottom_j.v
###############################################################
*/
/*
###############################################################
#  Generated by:      Cadence Innovus 17.12-s095_1
#  OS:                Linux x86_64(Host ID aduae260-lap)
#  Generated on:      Fri Mar 16 12:46:35 2018
#  Design:            c880
#  Command:           saveDesign database/design.final.enc
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 17.20-p003_1
// Generated on: Mar 16 2018 12:46:20 +04 (Mar 16 2018 08:46:20 UTC)
// Verification Directory fv/c880 
module bottom (
	G1GAT, 
	G8GAT, 
	G17GAT, 
	G26GAT, 
	G29GAT, 
	G36GAT, 
	G42GAT, 
	G51GAT, 
	G55GAT, 
	G59GAT, 
	G75GAT, 
	G80GAT, 
	G91GAT, 
	G96GAT, 
	G101GAT, 
	G106GAT, 
	G111GAT, 
	G116GAT, 
	G121GAT, 
	G130GAT, 
	G138GAT, 
	G143GAT, 
	G149GAT, 
	G159GAT, 
	G165GAT, 
	G171GAT, 
	G177GAT, 
	G183GAT, 
	G189GAT, 
	G195GAT, 
	G201GAT, 
	G207GAT, 
	G210GAT, 
	G219GAT, 
	G228GAT, 
	G237GAT, 
	G246GAT, 
	G255GAT, 
	G260GAT, 
	G261GAT, 
	G267GAT, 
	G268GAT, 
	g46069_ZN, 
	g46072_ZN, 
	g46077_ZN, 
	g46127_ZN, 
	g46067_ZN, 
	g46098_ZN, 
	g46109_CO, 
	g46074_ZN, 
	g46271_ZN, 
	g46097_ZN, 
	g46084_ZN, 
	g46085_ZN, 
	g46109_S, 
	g46092_ZN, 
	g46103_ZN, 
	g46093_ZN, 
	g46112_ZN, 
	g46119_ZN, 
	g46124_ZN, 
	g46111_ZN, 
	g46125_ZN, 
	g46091_ZN, 
	g46129_ZN, 
	g46150_ZN, 
	g46117_ZN, 
	g46139_ZN, 
	g46275_ZN, 
	g46270_ZN, 
	g46135_ZN, 
	g46148_ZN, 
	g46176_ZN, 
	g46160_ZN, 
	g46122_ZN, 
	g46142_ZN, 
	g46157_ZN, 
	g46273_ZN, 
	g46168_ZN, 
	g46187_ZN, 
	g46181_ZN, 
	g46175_ZN, 
	g46197_ZN, 
	g46281_ZN, 
	g46191_ZN, 
	g46264_ZN, 
	g46195_ZN, 
	g46208_ZN, 
	g46276_ZN, 
	g46250_ZN, 
	g46202_ZN, 
	g46232_ZN, 
	g46221_ZN, 
	g46254_ZN, 
	g46215_ZN, 
	g46237_ZN, 
	g46234_ZN, 
	g46251_ZN, 
	g46226_ZN, 
	g46228_ZN, 
	g46240_ZN, 
	g46259_ZN, 
	g46230_ZN, 
	g46241_ZN, 
	G388GAT, 
	G389GAT, 
	G390GAT, 
	G418GAT, 
	G420GAT, 
	G421GAT, 
	G446GAT, 
	G767GAT, 
	G768GAT, 
	G850GAT, 
	G866GAT, 
	G874GAT, 
	G878GAT, 
	G879GAT, 
	G880GAT, 
	g46067_A, 
	g46075_A1, 
	g46077_A1, 
	g46078_B1, 
	g46085_A, 
	g46089_A, 
	g46093_A, 
	g46089_C1, 
	g46078_A, 
	g46119_A, 
	g46092_A1, 
	g46071_C2, 
	g46071_A, 
	g46074_A2, 
	g46097_B2, 
	g46091_B1, 
	g46111_A, 
	g46127_A2, 
	g46127_A1, 
	g46138_A, 
	g46126_A1, 
	g46125_A1, 
	g46139_A1, 
	g46124_B1, 
	g46085_B1, 
	g46148_A1, 
	g46109_A, 
	g46150_A1, 
	g46118_B1, 
	g46165_A, 
	g46118_A, 
	g46178_A1, 
	g46124_B2, 
	g46157_A, 
	g46177_A, 
	g46281_A1, 
	g46175_A, 
	g46181_A, 
	g46208_A, 
	g46191_B1, 
	g46207_A1, 
	g46197_A1, 
	g46202_A, 
	g46129_A2, 
	g46131_A, 
	g46215_A1, 
	g46210_C1, 
	g46240_A, 
	g46210_A, 
	g46226_A1, 
	g46248_A1, 
	g46160_B2, 
	g46175_C2, 
	g46237_A, 
	g46236_A1, 
	g46232_C1, 
	g46215_A2, 
	g46109_B, 
	g46142_A2, 
	g46236_B1);
   input G1GAT;
   input G8GAT;
   input G17GAT;
   input G26GAT;
   input G29GAT;
   input G36GAT;
   input G42GAT;
   input G51GAT;
   input G55GAT;
   input G59GAT;
   input G75GAT;
   input G80GAT;
   input G91GAT;
   input G96GAT;
   input G101GAT;
   input G106GAT;
   input G111GAT;
   input G116GAT;
   input G121GAT;
   input G130GAT;
   input G138GAT;
   input G143GAT;
   input G149GAT;
   input G159GAT;
   input G165GAT;
   input G171GAT;
   input G177GAT;
   input G183GAT;
   input G189GAT;
   input G195GAT;
   input G201GAT;
   input G207GAT;
   input G210GAT;
   input G219GAT;
   input G228GAT;
   input G237GAT;
   input G246GAT;
   input G255GAT;
   input G260GAT;
   input G261GAT;
   input G267GAT;
   input G268GAT;
   input g46069_ZN;
   input g46072_ZN;
   input g46077_ZN;
   input g46127_ZN;
   input g46067_ZN;
   input g46098_ZN;
   input g46109_CO;
   input g46074_ZN;
   input g46271_ZN;
   input g46097_ZN;
   input g46084_ZN;
   input g46085_ZN;
   input g46109_S;
   input g46092_ZN;
   input g46103_ZN;
   input g46093_ZN;
   input g46112_ZN;
   input g46119_ZN;
   input g46124_ZN;
   input g46111_ZN;
   input g46125_ZN;
   input g46091_ZN;
   input g46129_ZN;
   input g46150_ZN;
   input g46117_ZN;
   input g46139_ZN;
   input g46275_ZN;
   input g46270_ZN;
   input g46135_ZN;
   input g46148_ZN;
   input g46176_ZN;
   input g46160_ZN;
   input g46122_ZN;
   input g46142_ZN;
   input g46157_ZN;
   input g46273_ZN;
   input g46168_ZN;
   input g46187_ZN;
   input g46181_ZN;
   input g46175_ZN;
   input g46197_ZN;
   input g46281_ZN;
   input g46191_ZN;
   input g46264_ZN;
   input g46195_ZN;
   input g46208_ZN;
   input g46276_ZN;
   input g46250_ZN;
   input g46202_ZN;
   input g46232_ZN;
   input g46221_ZN;
   input g46254_ZN;
   input g46215_ZN;
   input g46237_ZN;
   input g46234_ZN;
   input g46251_ZN;
   input g46226_ZN;
   input g46228_ZN;
   input g46240_ZN;
   input g46259_ZN;
   input g46230_ZN;
   input g46241_ZN;
   output G388GAT;
   output G389GAT;
   output G390GAT;
   output G418GAT;
   output G420GAT;
   output G421GAT;
   output G446GAT;
   output G767GAT;
   output G768GAT;
   output G850GAT;
   output G866GAT;
   output G874GAT;
   output G878GAT;
   output G879GAT;
   output G880GAT;
   output g46067_A;
   output g46075_A1;
   output g46077_A1;
   output g46078_B1;
   output g46085_A;
   output g46089_A;
   output g46093_A;
   output g46089_C1;
   output g46078_A;
   output g46119_A;
   output g46092_A1;
   output g46071_C2;
   output g46071_A;
   output g46074_A2;
   output g46097_B2;
   output g46091_B1;
   output g46111_A;
   output g46127_A2;
   output g46127_A1;
   output g46138_A;
   output g46126_A1;
   output g46125_A1;
   output g46139_A1;
   output g46124_B1;
   output g46085_B1;
   output g46148_A1;
   output g46109_A;
   output g46150_A1;
   output g46118_B1;
   output g46165_A;
   output g46118_A;
   output g46178_A1;
   output g46124_B2;
   output g46157_A;
   output g46177_A;
   output g46281_A1;
   output g46175_A;
   output g46181_A;
   output g46208_A;
   output g46191_B1;
   output g46207_A1;
   output g46197_A1;
   output g46202_A;
   output g46129_A2;
   output g46131_A;
   output g46215_A1;
   output g46210_C1;
   output g46240_A;
   output g46210_A;
   output g46226_A1;
   output g46248_A1;
   output g46160_B2;
   output g46175_C2;
   output g46237_A;
   output g46236_A1;
   output g46232_C1;
   output g46215_A2;
   output g46109_B;
   output g46142_A2;
   output g46236_B1;

   // Internal wires
   wire bottom_n_0;
   wire bottom_n_182;
   wire bottom_n_186;
   wire bottom_n_198;
   wire bottom_n_199;
   wire bottom_n_202;
   wire bottom_n_205;
   wire bottom_n_208;
   wire bottom_n_209;
   wire bottom_n_277;
   wire bottom_n_278;
   wire bottom_n_279;
   wire bottom_n_280;
   wire bottom_n_281;
   wire bottom_n_282;
   wire bottom_n_283;
   wire bottom_n_284;
   wire bottom_n_285;
   wire bottom_n_286;
   wire bottom_n_287;
   wire bottom_n_288;
   wire bottom_n_289;
   wire bottom_n_290;
   wire bottom_n_291;
   wire bottom_n_292;
   wire bottom_n_293;
   wire bottom_n_294;
   wire bottom_n_295;
   wire bottom_n_296;
   wire bottom_n_297;
   wire bottom_n_298;
   wire bottom_n_299;
   wire bottom_n_300;
   wire bottom_n_301;
   wire bottom_n_302;
   wire bottom_n_303;
   wire bottom_n_304;
   wire bottom_n_305;
   wire bottom_n_306;
   wire bottom_n_307;
   wire bottom_n_308;

   NAND3_X1 g46063 (.A1(g46069_ZN),
	.A2(g46072_ZN),
	.A3(bottom_n_277),
	.ZN(G880GAT));
   OAI211_X1 g46064 (.A(g46077_ZN),
	.B(bottom_n_278),
	.C1(bottom_n_202),
	.C2(g46127_ZN),
	.ZN(G874GAT));
   NAND2_X1 g46062 (.A1(bottom_n_208),
	.A2(g46067_ZN),
	.ZN(G879GAT));
   OAI221_X1 g46061 (.A(g46098_ZN),
	.B1(bottom_n_209),
	.B2(bottom_n_279),
	.C1(bottom_n_199),
	.C2(bottom_n_198),
	.ZN(G878GAT));
   OAI22_X1 g46065 (.A1(bottom_n_209),
	.A2(g46109_CO),
	.B1(g46109_A),
	.B2(g46109_B),
	.ZN(G866GAT));
   AOI221_X1 g46066 (.A(bottom_n_280),
	.B1(bottom_n_205),
	.B2(G228GAT),
	.C1(g46074_ZN),
	.C2(bottom_n_182),
	.ZN(bottom_n_208));
   AOI211_X1 g46068 (.A(g46271_ZN),
	.B(bottom_n_205),
	.C1(g46074_ZN),
	.C2(g46097_ZN),
	.ZN(g46067_A));
   AOI21_X1 g46073 (.A(G228GAT),
	.B1(g46075_A1),
	.B2(G219GAT),
	.ZN(bottom_n_202));
   NOR2_X1 g46070 (.A1(bottom_n_199),
	.A2(g46084_ZN),
	.ZN(bottom_n_209));
   NAND3_X1 g46083 (.A1(g46085_ZN),
	.A2(g46109_S),
	.A3(G219GAT),
	.ZN(bottom_n_198));
   INV_X1 g46079 (.A(g46077_A1),
	.ZN(g46075_A1));
   OAI21_X1 g46076 (.A(bottom_n_186),
	.B1(g46092_ZN),
	.B2(g46093_A),
	.ZN(bottom_n_199));
   NAND2_X1 g46080 (.A1(g46092_ZN),
	.A2(bottom_n_281),
	.ZN(g46077_A1));
   AOI21_X1 g46087 (.A(G228GAT),
	.B1(g46103_ZN),
	.B2(G219GAT),
	.ZN(g46078_B1));
   NAND3_X1 g46082 (.A1(g46093_ZN),
	.A2(g46112_ZN),
	.A3(g46092_A1),
	.ZN(bottom_n_186));
   OAI211_X1 g46096 (.A(g46119_ZN),
	.B(bottom_n_282),
	.C1(g46124_ZN),
	.C2(bottom_n_283),
	.ZN(G850GAT));
   INV_X1 g46099 (.A(bottom_n_284),
	.ZN(g46085_A));
   AND3_X1 g46086 (.A1(g46097_ZN),
	.A2(bottom_n_205),
	.A3(G219GAT),
	.ZN(bottom_n_182));
   OAI211_X1 g46100 (.A(g46097_B2),
	.B(bottom_n_285),
	.C1(g46111_ZN),
	.C2(g46127_A2),
	.ZN(bottom_n_284));
   NAND3_X1 g46108 (.A1(g46125_ZN),
	.A2(bottom_n_286),
	.A3(G219GAT),
	.ZN(g46089_A));
   INV_X1 g46090 (.A(g46091_ZN),
	.ZN(bottom_n_277));
   NAND2_X1 g46094 (.A1(g46074_A2),
	.A2(bottom_n_285),
	.ZN(g46093_A));
   OR2_X1 g46105 (.A1(g46109_S),
	.A2(g46271_ZN),
	.ZN(bottom_n_279));
   AOI21_X1 g46107 (.A(G228GAT),
	.B1(g46129_ZN),
	.B2(G219GAT),
	.ZN(g46089_C1));
   OR4_X1 g46088 (.A1(bottom_n_287),
	.A2(g46129_ZN),
	.A3(g46125_A1),
	.A4(g46150_ZN),
	.ZN(bottom_n_281));
   NAND3_X1 g46115 (.A1(g46124_ZN),
	.A2(G219GAT),
	.A3(G261GAT),
	.ZN(bottom_n_282));
   INV_X1 g46116 (.A(g46117_ZN),
	.ZN(g46078_A));
   OAI221_X1 g46120 (.A(bottom_n_288),
	.B1(g46139_ZN),
	.B2(g46275_ZN),
	.C1(bottom_n_289),
	.C2(g46270_ZN),
	.ZN(g46119_A));
   NOR2_X1 g46104 (.A1(bottom_n_287),
	.A2(g46150_ZN),
	.ZN(g46092_A1));
   NAND2_X1 g46106 (.A1(g46135_ZN),
	.A2(G219GAT),
	.ZN(g46071_C2));
   INV_X1 g46123 (.A(g46129_ZN),
	.ZN(bottom_n_286));
   AOI221_X1 g46133 (.A(bottom_n_290),
	.B1(G210GAT),
	.B2(G106GAT),
	.C1(g46178_A1),
	.C2(G183GAT),
	.ZN(g46071_A));
   NOR2_X1 g46102 (.A1(g46127_A1),
	.A2(g46148_ZN),
	.ZN(g46074_A2));
   AOI221_X1 g46114 (.A(g46176_ZN),
	.B1(g46160_ZN),
	.B2(G246GAT),
	.C1(g46127_A2),
	.C2(G237GAT),
	.ZN(bottom_n_278));
   XNOR2_X1 g46101 (.A(g46122_ZN),
	.B(G207GAT),
	.ZN(G768GAT));
   XOR2_X1 g46134 (.A(g46085_B1),
	.B(G165GAT),
	.Z(bottom_n_205));
   INV_X1 g46137 (.A(g46142_ZN),
	.ZN(bottom_n_287));
   INV_X1 g46110 (.A(g46148_ZN),
	.ZN(g46097_B2));
   OAI21_X1 g46132 (.A(bottom_n_291),
	.B1(g46157_ZN),
	.B2(bottom_n_292),
	.ZN(bottom_n_280));
   XOR2_X1 g46136 (.A(bottom_n_293),
	.B(G171GAT),
	.Z(g46091_B1));
   NAND2_X1 g46147 (.A1(g46148_A1),
	.A2(G171GAT),
	.ZN(g46111_A));
   XNOR2_X1 g46121 (.A(bottom_n_294),
	.B(G130GAT),
	.ZN(G767GAT));
   AND2_X1 g46140 (.A1(g46160_ZN),
	.A2(G177GAT),
	.ZN(g46127_A2));
   NOR2_X1 g46141 (.A1(g46160_ZN),
	.A2(G177GAT),
	.ZN(g46127_A1));
   NAND2_X1 g46143 (.A1(g46118_B1),
	.A2(G195GAT),
	.ZN(g46138_A));
   NAND2_X1 g46144 (.A1(g46165_A),
	.A2(G189GAT),
	.ZN(g46126_A1));
   NOR2_X1 g46145 (.A1(g46118_B1),
	.A2(G195GAT),
	.ZN(g46125_A1));
   AOI21_X1 g46146 (.A(bottom_n_295),
	.B1(g46270_ZN),
	.B2(bottom_n_296),
	.ZN(bottom_n_290));
   NAND2_X1 g46149 (.A1(g46157_ZN),
	.A2(g46273_ZN),
	.ZN(bottom_n_285));
   INV_X1 g46153 (.A(g46139_A1),
	.ZN(bottom_n_289));
   AOI222_X1 g46174 (.A1(g46178_A1),
	.A2(G201GAT),
	.B1(G255GAT),
	.B2(G267GAT),
	.C1(G210GAT),
	.C2(G121GAT),
	.ZN(bottom_n_288));
   AOI22_X1 g46180 (.A1(g46178_A1),
	.A2(G165GAT),
	.B1(G210GAT),
	.B2(G91GAT),
	.ZN(bottom_n_291));
   NAND2_X1 g46154 (.A1(bottom_n_297),
	.A2(g46168_ZN),
	.ZN(g46139_A1));
   NAND2_X1 g46155 (.A1(g46168_ZN),
	.A2(g46236_A1),
	.ZN(g46124_B1));
   INV_X1 g46156 (.A(g46157_ZN),
	.ZN(g46085_B1));
   INV_X1 g46158 (.A(bottom_n_293),
	.ZN(g46148_A1));
   AOI21_X1 g46161 (.A(bottom_n_298),
	.B1(g46187_ZN),
	.B2(G91GAT),
	.ZN(g46109_A));
   INV_X1 g46163 (.A(bottom_n_295),
	.ZN(g46150_A1));
   XNOR2_X1 g46151 (.A(g46181_ZN),
	.B(bottom_n_299),
	.ZN(bottom_n_294));
   AOI21_X1 g46159 (.A(g46175_ZN),
	.B1(g46187_ZN),
	.B2(G101GAT),
	.ZN(bottom_n_293));
   OAI221_X1 g46162 (.A(g46197_ZN),
	.B1(g46281_ZN),
	.B2(g46237_A),
	.C1(bottom_n_300),
	.C2(bottom_n_301),
	.ZN(g46118_B1));
   AOI21_X1 g46164 (.A(bottom_n_302),
	.B1(g46187_ZN),
	.B2(G111GAT),
	.ZN(bottom_n_295));
   OAI221_X1 g46166 (.A(g46197_ZN),
	.B1(g46281_ZN),
	.B2(bottom_n_303),
	.C1(g46191_ZN),
	.C2(g46264_ZN),
	.ZN(g46165_A));
   OAI21_X1 g46171 (.A(bottom_n_304),
	.B1(g46195_ZN),
	.B2(bottom_n_305),
	.ZN(g46118_A));
   NAND2_X1 g46169 (.A1(bottom_n_306),
	.A2(g46175_A),
	.ZN(bottom_n_298));
   INV_X1 g46190 (.A(g46195_ZN),
	.ZN(g46178_A1));
   INV_X1 g46167 (.A(g46124_B2),
	.ZN(bottom_n_297));
   AOI22_X1 g46189 (.A1(g46208_ZN),
	.A2(G143GAT),
	.B1(G138GAT),
	.B2(G8GAT),
	.ZN(bottom_n_306));
   OAI21_X1 g46170 (.A(g46197_ZN),
	.B1(g46191_ZN),
	.B2(g46276_ZN),
	.ZN(g46124_B2));
   OAI21_X1 g46172 (.A(g46197_ZN),
	.B1(g46191_ZN),
	.B2(bottom_n_0),
	.ZN(bottom_n_302));
   OAI211_X1 g46179 (.A(g46175_A),
	.B(g46250_ZN),
	.C1(g46208_A),
	.C2(g46264_ZN),
	.ZN(g46157_A));
   XNOR2_X1 g46183 (.A(g46202_ZN),
	.B(G106GAT),
	.ZN(bottom_n_299));
   INV_X1 g46196 (.A(g46175_A),
	.ZN(g46177_A));
   NOR3_X1 g46194 (.A1(g46232_ZN),
	.A2(g46221_ZN),
	.A3(g46254_ZN),
	.ZN(g46281_A1));
   NAND3_X1 g46198 (.A1(g46197_A1),
	.A2(g46215_ZN),
	.A3(G17GAT),
	.ZN(g46175_A));
   XNOR2_X1 g46199 (.A(g46237_ZN),
	.B(g46234_ZN),
	.ZN(g46181_A));
   NAND3_X1 g46209 (.A1(g46215_ZN),
	.A2(g46251_ZN),
	.A3(G55GAT),
	.ZN(g46208_A));
   OAI221_X1 g46211 (.A(G149GAT),
	.B1(g46251_ZN),
	.B2(g46215_A2),
	.C1(g46215_A2),
	.C2(G17GAT),
	.ZN(bottom_n_300));
   NAND2_X1 g46203 (.A1(g46226_ZN),
	.A2(G390GAT),
	.ZN(G446GAT));
   NOR2_X1 g46204 (.A1(g46228_ZN),
	.A2(g46232_C1),
	.ZN(G418GAT));
   NAND2_X1 g46217 (.A1(bottom_n_307),
	.A2(G59GAT),
	.ZN(G420GAT));
   NAND2_X1 g46220 (.A1(g46240_ZN),
	.A2(G59GAT),
	.ZN(G421GAT));
   NOR2_X1 g46219 (.A1(g46240_A),
	.A2(g46259_ZN),
	.ZN(G389GAT));
   NOR2_X1 g46216 (.A1(g46215_A1),
	.A2(g46226_A1),
	.ZN(g46191_B1));
   INV_X1 g46224 (.A(g46228_ZN),
	.ZN(g46207_A1));
   INV_X1 g46225 (.A(g46230_ZN),
	.ZN(G390GAT));
   AOI21_X1 g46227 (.A(G228GAT),
	.B1(bottom_n_308),
	.B2(G219GAT),
	.ZN(bottom_n_283));
   NOR3_X1 g46229 (.A1(g46241_ZN),
	.A2(g46259_ZN),
	.A3(G268GAT),
	.ZN(g46197_A1));
   AND2_X1 g46218 (.A1(g46210_C1),
	.A2(G29GAT),
	.ZN(G388GAT));
   AOI21_X1 g46223 (.A(G246GAT),
	.B1(G237GAT),
	.B2(G165GAT),
	.ZN(bottom_n_292));
   XNOR2_X1 g46238 (.A(G91GAT),
	.B(G96GAT),
	.ZN(g46202_A));
   AOI22_X1 g46231 (.A1(G255GAT),
	.A2(G260GAT),
	.B1(G210GAT),
	.B2(G116GAT),
	.ZN(bottom_n_304));
   INV_X1 g46239 (.A(g46241_ZN),
	.ZN(bottom_n_307));
   NAND2_X1 g46252 (.A1(g46236_A1),
	.A2(bottom_n_308),
	.ZN(g46129_A2));
   NAND2_X1 g46247 (.A1(G210GAT),
	.A2(G268GAT),
	.ZN(g46131_A));
   NAND2_X1 g46245 (.A1(G26GAT),
	.A2(G51GAT),
	.ZN(g46215_A1));
   AND2_X1 g46246 (.A1(G75GAT),
	.A2(G42GAT),
	.ZN(g46210_C1));
   NAND2_X1 g46243 (.A1(G36GAT),
	.A2(G80GAT),
	.ZN(g46240_A));
   NAND2_X1 g46244 (.A1(G183GAT),
	.A2(G237GAT),
	.ZN(bottom_n_296));
   NAND2_X1 g46255 (.A1(G17GAT),
	.A2(G8GAT),
	.ZN(g46210_A));
   NAND2_X1 g46256 (.A1(G17GAT),
	.A2(G1GAT),
	.ZN(g46226_A1));
   INV_X1 g46272 (.A(G195GAT),
	.ZN(bottom_n_305));
   INV_X1 g46265 (.A(G116GAT),
	.ZN(bottom_n_303));
   INV_X1 g46262 (.A(G59GAT),
	.ZN(g46248_A1));
   INV_X1 g46279 (.A(G106GAT),
	.ZN(g46160_B2));
   INV_X1 g46268 (.A(G149GAT),
	.ZN(g46175_C2));
   INV_X1 g46280 (.A(G121GAT),
	.ZN(g46237_A));
   INV_X1 g46274 (.A(G261GAT),
	.ZN(bottom_n_308));
   INV_X1 g46267 (.A(G201GAT),
	.ZN(g46236_A1));
   INV_X1 g46278 (.A(G17GAT),
	.ZN(g46232_C1));
   INV_X1 g46269 (.A(G1GAT),
	.ZN(g46215_A2));
   INV_X1 g46261 (.A(G159GAT),
	.ZN(g46109_B));
   INV_X1 g46266 (.A(G189GAT),
	.ZN(g46142_A2));
   INV_X1 g46277 (.A(G183GAT),
	.ZN(g46236_B1));
   INV_X1 g46263 (.A(G143GAT),
	.ZN(bottom_n_0));
   AOI21_X1 g2 (.A(g46215_A2),
	.B1(G51GAT),
	.B2(G26GAT),
	.ZN(bottom_n_301));
endmodule

