/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID aduae260-lap)
#  Generated on:      Wed Sep 26 11:40:53 2018
#  Design:            c880
#  Command:           saveNetlist -module top outputs/top_j.v
###############################################################
*/
module top (
	G1GAT, 
	G8GAT, 
	G13GAT, 
	G17GAT, 
	G26GAT, 
	G29GAT, 
	G36GAT, 
	G42GAT, 
	G51GAT, 
	G55GAT, 
	G59GAT, 
	G68GAT, 
	G72GAT, 
	G73GAT, 
	G74GAT, 
	G75GAT, 
	G80GAT, 
	G85GAT, 
	G86GAT, 
	G87GAT, 
	G88GAT, 
	G89GAT, 
	G90GAT, 
	G96GAT, 
	G101GAT, 
	G111GAT, 
	G116GAT, 
	G126GAT, 
	G130GAT, 
	G135GAT, 
	G138GAT, 
	G146GAT, 
	G152GAT, 
	G153GAT, 
	G156GAT, 
	G159GAT, 
	G165GAT, 
	G171GAT, 
	G177GAT, 
	G183GAT, 
	G189GAT, 
	G195GAT, 
	G201GAT, 
	G210GAT, 
	G219GAT, 
	G228GAT, 
	G237GAT, 
	G246GAT, 
	G255GAT, 
	G259GAT, 
	G261GAT, 
	bottom_g46091_B1, 
	bottom_g46127_A2, 
	bottom_g46067_A, 
	bottom_g46071_A, 
	bottom_g46071_C2, 
	bottom_g46078_A, 
	bottom_g46078_B1, 
	bottom_g46075_A1, 
	bottom_g46127_A1, 
	bottom_g46077_A1, 
	bottom_g46074_A2, 
	bottom_g46085_A, 
	bottom_g46085_B1, 
	bottom_g46089_A, 
	bottom_g46089_C1, 
	bottom_g46092_A1, 
	bottom_g46150_A1, 
	bottom_g46093_A, 
	bottom_g46119_A, 
	bottom_g46097_B2, 
	bottom_g46111_A, 
	bottom_g46125_A1, 
	bottom_g46126_A1, 
	bottom_g46118_A, 
	bottom_g46118_B1, 
	bottom_g46124_B1, 
	bottom_g46124_B2, 
	bottom_g46148_A1, 
	bottom_g46178_A1, 
	bottom_g46131_A, 
	bottom_g46109_A, 
	bottom_g46109_B, 
	bottom_g46138_A, 
	bottom_g46139_A1, 
	bottom_g46129_A2, 
	bottom_g46142_A2, 
	bottom_g46165_A, 
	bottom_g46157_A, 
	bottom_g46160_B2, 
	bottom_g46177_A, 
	bottom_g46181_A, 
	bottom_g46175_A, 
	bottom_g46208_A, 
	bottom_g46175_C2, 
	bottom_g46215_A2, 
	bottom_g46191_B1, 
	bottom_g46197_A1, 
	bottom_g46202_A, 
	bottom_g46207_A1, 
	bottom_g46210_A, 
	bottom_g46210_C1, 
	bottom_g46232_C1, 
	bottom_g46215_A1, 
	bottom_g46236_A1, 
	bottom_g46236_B1, 
	bottom_g46226_A1, 
	bottom_g46237_A, 
	bottom_g46240_A, 
	bottom_g46248_A1, 
	bottom_g46281_A1, 
	G391GAT, 
	G419GAT, 
	G422GAT, 
	G423GAT, 
	G447GAT, 
	G448GAT, 
	G449GAT, 
	G450GAT, 
	G863GAT, 
	G864GAT, 
	G865GAT, 
	bottom_g46069_ZN, 
	bottom_g46072_ZN, 
	bottom_g46067_ZN, 
	bottom_g46074_ZN, 
	bottom_g46077_ZN, 
	bottom_g46084_ZN, 
	bottom_g46085_ZN, 
	bottom_g46092_ZN, 
	bottom_g46093_ZN, 
	bottom_g46098_ZN, 
	bottom_g46103_ZN, 
	bottom_g46119_ZN, 
	bottom_g46097_ZN, 
	bottom_g46091_ZN, 
	bottom_g46112_ZN, 
	bottom_g46117_ZN, 
	bottom_g46124_ZN, 
	bottom_g46125_ZN, 
	bottom_g46109_CO, 
	bottom_g46109_S, 
	bottom_g46127_ZN, 
	bottom_g46129_ZN, 
	bottom_g46135_ZN, 
	bottom_g46111_ZN, 
	bottom_g46139_ZN, 
	bottom_g46142_ZN, 
	bottom_g46148_ZN, 
	bottom_g46150_ZN, 
	bottom_g46176_ZN, 
	bottom_g46122_ZN, 
	bottom_g46157_ZN, 
	bottom_g46160_ZN, 
	bottom_g46168_ZN, 
	bottom_g46181_ZN, 
	bottom_g46187_ZN, 
	bottom_g46195_ZN, 
	bottom_g46175_ZN, 
	bottom_g46191_ZN, 
	bottom_g46197_ZN, 
	bottom_g46208_ZN, 
	bottom_g46202_ZN, 
	bottom_g46232_ZN, 
	bottom_g46226_ZN, 
	bottom_g46237_ZN, 
	bottom_g46240_ZN, 
	bottom_g46221_ZN, 
	bottom_g46228_ZN, 
	bottom_g46230_ZN, 
	bottom_g46234_ZN, 
	bottom_g46250_ZN, 
	bottom_g46251_ZN, 
	bottom_g46254_ZN, 
	bottom_g46241_ZN, 
	bottom_g46273_ZN, 
	bottom_g46271_ZN, 
	bottom_g46259_ZN, 
	bottom_g46276_ZN, 
	bottom_g46275_ZN, 
	bottom_g46270_ZN, 
	bottom_g46264_ZN, 
	bottom_g46281_ZN);
   input G1GAT;
   input G8GAT;
   input G13GAT;
   input G17GAT;
   input G26GAT;
   input G29GAT;
   input G36GAT;
   input G42GAT;
   input G51GAT;
   input G55GAT;
   input G59GAT;
   input G68GAT;
   input G72GAT;
   input G73GAT;
   input G74GAT;
   input G75GAT;
   input G80GAT;
   input G85GAT;
   input G86GAT;
   input G87GAT;
   input G88GAT;
   input G89GAT;
   input G90GAT;
   input G96GAT;
   input G101GAT;
   input G111GAT;
   input G116GAT;
   input G126GAT;
   input G130GAT;
   input G135GAT;
   input G138GAT;
   input G146GAT;
   input G152GAT;
   input G153GAT;
   input G156GAT;
   input G159GAT;
   input G165GAT;
   input G171GAT;
   input G177GAT;
   input G183GAT;
   input G189GAT;
   input G195GAT;
   input G201GAT;
   input G210GAT;
   input G219GAT;
   input G228GAT;
   input G237GAT;
   input G246GAT;
   input G255GAT;
   input G259GAT;
   input G261GAT;
   input bottom_g46091_B1;
   input bottom_g46127_A2;
   input bottom_g46067_A;
   input bottom_g46071_A;
   input bottom_g46071_C2;
   input bottom_g46078_A;
   input bottom_g46078_B1;
   input bottom_g46075_A1;
   input bottom_g46127_A1;
   input bottom_g46077_A1;
   input bottom_g46074_A2;
   input bottom_g46085_A;
   input bottom_g46085_B1;
   input bottom_g46089_A;
   input bottom_g46089_C1;
   input bottom_g46092_A1;
   input bottom_g46150_A1;
   input bottom_g46093_A;
   input bottom_g46119_A;
   input bottom_g46097_B2;
   input bottom_g46111_A;
   input bottom_g46125_A1;
   input bottom_g46126_A1;
   input bottom_g46118_A;
   input bottom_g46118_B1;
   input bottom_g46124_B1;
   input bottom_g46124_B2;
   input bottom_g46148_A1;
   input bottom_g46178_A1;
   input bottom_g46131_A;
   input bottom_g46109_A;
   input bottom_g46109_B;
   input bottom_g46138_A;
   input bottom_g46139_A1;
   input bottom_g46129_A2;
   input bottom_g46142_A2;
   input bottom_g46165_A;
   input bottom_g46157_A;
   input bottom_g46160_B2;
   input bottom_g46177_A;
   input bottom_g46181_A;
   input bottom_g46175_A;
   input bottom_g46208_A;
   input bottom_g46175_C2;
   input bottom_g46215_A2;
   input bottom_g46191_B1;
   input bottom_g46197_A1;
   input bottom_g46202_A;
   input bottom_g46207_A1;
   input bottom_g46210_A;
   input bottom_g46210_C1;
   input bottom_g46232_C1;
   input bottom_g46215_A1;
   input bottom_g46236_A1;
   input bottom_g46236_B1;
   input bottom_g46226_A1;
   input bottom_g46237_A;
   input bottom_g46240_A;
   input bottom_g46248_A1;
   input bottom_g46281_A1;
   output G391GAT;
   output G419GAT;
   output G422GAT;
   output G423GAT;
   output G447GAT;
   output G448GAT;
   output G449GAT;
   output G450GAT;
   output G863GAT;
   output G864GAT;
   output G865GAT;
   output bottom_g46069_ZN;
   output bottom_g46072_ZN;
   output bottom_g46067_ZN;
   output bottom_g46074_ZN;
   output bottom_g46077_ZN;
   output bottom_g46084_ZN;
   output bottom_g46085_ZN;
   output bottom_g46092_ZN;
   output bottom_g46093_ZN;
   output bottom_g46098_ZN;
   output bottom_g46103_ZN;
   output bottom_g46119_ZN;
   output bottom_g46097_ZN;
   output bottom_g46091_ZN;
   output bottom_g46112_ZN;
   output bottom_g46117_ZN;
   output bottom_g46124_ZN;
   output bottom_g46125_ZN;
   output bottom_g46109_CO;
   output bottom_g46109_S;
   output bottom_g46127_ZN;
   output bottom_g46129_ZN;
   output bottom_g46135_ZN;
   output bottom_g46111_ZN;
   output bottom_g46139_ZN;
   output bottom_g46142_ZN;
   output bottom_g46148_ZN;
   output bottom_g46150_ZN;
   output bottom_g46176_ZN;
   output bottom_g46122_ZN;
   output bottom_g46157_ZN;
   output bottom_g46160_ZN;
   output bottom_g46168_ZN;
   output bottom_g46181_ZN;
   output bottom_g46187_ZN;
   output bottom_g46195_ZN;
   output bottom_g46175_ZN;
   output bottom_g46191_ZN;
   output bottom_g46197_ZN;
   output bottom_g46208_ZN;
   output bottom_g46202_ZN;
   output bottom_g46232_ZN;
   output bottom_g46226_ZN;
   output bottom_g46237_ZN;
   output bottom_g46240_ZN;
   output bottom_g46221_ZN;
   output bottom_g46228_ZN;
   output bottom_g46230_ZN;
   output bottom_g46234_ZN;
   output bottom_g46250_ZN;
   output bottom_g46251_ZN;
   output bottom_g46254_ZN;
   output bottom_g46241_ZN;
   output bottom_g46273_ZN;
   output bottom_g46271_ZN;
   output bottom_g46259_ZN;
   output bottom_g46276_ZN;
   output bottom_g46275_ZN;
   output bottom_g46270_ZN;
   output bottom_g46264_ZN;
   output bottom_g46281_ZN;

   // Internal wires
   wire top_n_193;
   wire top_n_194;
   wire top_n_214;
   wire top_n_277;
   wire top_n_278;
   wire top_n_279;
   wire top_n_280;
   wire top_n_281;
   wire top_n_282;
   wire top_n_283;
   wire top_n_284;
   wire top_n_285;
   wire top_n_286;
   wire top_n_287;
   wire top_n_288;
   wire top_n_289;
   wire top_n_290;
   wire top_n_291;
   wire top_n_292;
   wire top_n_293;
   wire top_n_294;
   wire top_n_295;
   wire top_n_296;
   wire top_n_297;
   wire top_n_298;
   wire top_n_299;
   wire top_n_300;
   wire top_n_301;
   wire top_n_302;
   wire top_n_303;
   wire top_n_304;

   OAI211_X1 g46069 (.A(bottom_g46091_B1),
	.B(G219GAT),
	.C1(top_n_214),
	.C2(bottom_g46127_A2),
	.ZN(bottom_g46069_ZN));
   OR4_X1 g46072 (.A1(top_n_214),
	.A2(bottom_g46091_B1),
	.A3(bottom_g46127_A2),
	.A4(bottom_g46271_ZN),
	.ZN(bottom_g46072_ZN));
   INV_X1 g46067 (.A(bottom_g46067_A),
	.ZN(bottom_g46067_ZN));
   OAI221_X1 g46071 (.A(bottom_g46071_A),
	.B1(top_n_194),
	.B2(bottom_g46135_ZN),
	.C1(top_n_193),
	.C2(bottom_g46071_C2),
	.ZN(G863GAT));
   OAI221_X1 g46078 (.A(bottom_g46078_A),
	.B1(bottom_g46078_B1),
	.B2(top_n_277),
	.C1(bottom_g46103_ZN),
	.C2(top_n_278),
	.ZN(G864GAT));
   NOR2_X1 g46075 (.A1(bottom_g46075_A1),
	.A2(bottom_g46127_A1),
	.ZN(top_n_214));
   NAND2_X1 g46074 (.A1(bottom_g46077_A1),
	.A2(bottom_g46074_A2),
	.ZN(bottom_g46074_ZN));
   NAND3_X1 g46077 (.A1(bottom_g46077_A1),
	.A2(bottom_g46127_ZN),
	.A3(G219GAT),
	.ZN(bottom_g46077_ZN));
   AOI21_X1 g46081 (.A(G228GAT),
	.B1(top_n_193),
	.B2(G219GAT),
	.ZN(top_n_194));
   INV_X1 g46084 (.A(bottom_g46085_ZN),
	.ZN(bottom_g46084_ZN));
   AOI21_X1 g46085 (.A(bottom_g46085_A),
	.B1(bottom_g46085_B1),
	.B2(G165GAT),
	.ZN(bottom_g46085_ZN));
   OAI211_X1 g46089 (.A(bottom_g46089_A),
	.B(top_n_279),
	.C1(bottom_g46089_C1),
	.C2(bottom_g46125_ZN),
	.ZN(G865GAT));
   OAI21_X1 g46095 (.A(bottom_g46142_ZN),
	.B1(bottom_g46112_ZN),
	.B2(top_n_280),
	.ZN(top_n_193));
   AOI22_X1 g46092 (.A1(bottom_g46092_A1),
	.A2(top_n_280),
	.B1(bottom_g46150_A1),
	.B2(G183GAT),
	.ZN(bottom_g46092_ZN));
   INV_X1 g46093 (.A(bottom_g46093_A),
	.ZN(bottom_g46093_ZN));
   AOI21_X1 g46098 (.A(top_n_281),
	.B1(bottom_g46109_S),
	.B2(G228GAT),
	.ZN(bottom_g46098_ZN));
   NOR2_X1 g46103 (.A1(bottom_g46112_ZN),
	.A2(top_n_282),
	.ZN(bottom_g46103_ZN));
   INV_X1 g46119 (.A(bottom_g46119_A),
	.ZN(bottom_g46119_ZN));
   AOI21_X1 g46097 (.A(bottom_g46111_ZN),
	.B1(bottom_g46127_A2),
	.B2(bottom_g46097_B2),
	.ZN(bottom_g46097_ZN));
   NAND2_X1 g46113 (.A1(top_n_277),
	.A2(G219GAT),
	.ZN(top_n_278));
   OAI221_X1 g46091 (.A(top_n_283),
	.B1(bottom_g46091_B1),
	.B2(top_n_284),
	.C1(bottom_g46111_A),
	.C2(bottom_g46275_ZN),
	.ZN(bottom_g46091_ZN));
   NOR2_X1 g46112 (.A1(bottom_g46129_ZN),
	.A2(bottom_g46125_A1),
	.ZN(bottom_g46112_ZN));
   OAI221_X1 g46117 (.A(top_n_285),
	.B1(bottom_g46126_A1),
	.B2(bottom_g46275_ZN),
	.C1(top_n_286),
	.C2(bottom_g46270_ZN),
	.ZN(bottom_g46117_ZN));
   AOI221_X1 g46118 (.A(bottom_g46118_A),
	.B1(bottom_g46118_B1),
	.B2(G246GAT),
	.C1(top_n_282),
	.C2(G237GAT),
	.ZN(top_n_279));
   OAI21_X1 g46124 (.A(bottom_g46139_ZN),
	.B1(bottom_g46124_B1),
	.B2(bottom_g46124_B2),
	.ZN(bottom_g46124_ZN));
   OR2_X1 g46125 (.A1(bottom_g46125_A1),
	.A2(top_n_282),
	.ZN(bottom_g46125_ZN));
   NAND2_X1 g46128 (.A1(bottom_g46142_ZN),
	.A2(bottom_g46126_A1),
	.ZN(top_n_277));
   AOI222_X1 g46130 (.A1(bottom_g46148_A1),
	.A2(G246GAT),
	.B1(bottom_g46178_A1),
	.B2(G171GAT),
	.C1(G210GAT),
	.C2(G96GAT),
	.ZN(top_n_283));
   OAI221_X1 g46131 (.A(bottom_g46131_A),
	.B1(bottom_g46109_A),
	.B2(top_n_287),
	.C1(bottom_g46195_ZN),
	.C2(bottom_g46109_B),
	.ZN(top_n_281));
   HA_X1 g46109 (.A(bottom_g46109_A),
	.B(bottom_g46109_B),
	.CO(bottom_g46109_CO),
	.S(bottom_g46109_S));
   NAND2_X1 g46126 (.A1(bottom_g46126_A1),
	.A2(bottom_g46138_A),
	.ZN(top_n_280));
   OR2_X1 g46127 (.A1(bottom_g46127_A1),
	.A2(bottom_g46127_A2),
	.ZN(bottom_g46127_ZN));
   AOI22_X1 g46129 (.A1(bottom_g46139_A1),
	.A2(bottom_g46129_A2),
	.B1(G201GAT),
	.B2(G261GAT),
	.ZN(bottom_g46129_ZN));
   XNOR2_X1 g46135 (.A(bottom_g46150_A1),
	.B(G183GAT),
	.ZN(bottom_g46135_ZN));
   INV_X1 g46111 (.A(bottom_g46111_A),
	.ZN(bottom_g46111_ZN));
   INV_X1 g46138 (.A(bottom_g46138_A),
	.ZN(top_n_282));
   NAND2_X1 g46139 (.A1(bottom_g46139_A1),
	.A2(G201GAT),
	.ZN(bottom_g46139_ZN));
   NAND2_X1 g46142 (.A1(top_n_286),
	.A2(bottom_g46142_A2),
	.ZN(bottom_g46142_ZN));
   NOR2_X1 g46148 (.A1(bottom_g46148_A1),
	.A2(G171GAT),
	.ZN(bottom_g46148_ZN));
   NOR2_X1 g46150 (.A1(bottom_g46150_A1),
	.A2(G183GAT),
	.ZN(bottom_g46150_ZN));
   AOI222_X1 g46173 (.A1(bottom_g46178_A1),
	.A2(G189GAT),
	.B1(G255GAT),
	.B2(G259GAT),
	.C1(G210GAT),
	.C2(G111GAT),
	.ZN(top_n_285));
   INV_X1 g46176 (.A(top_n_288),
	.ZN(bottom_g46176_ZN));
   XNOR2_X1 g46122 (.A(top_n_289),
	.B(top_n_290),
	.ZN(bottom_g46122_ZN));
   INV_X1 g46165 (.A(bottom_g46165_A),
	.ZN(top_n_286));
   AOI22_X1 g46178 (.A1(bottom_g46178_A1),
	.A2(G177GAT),
	.B1(G210GAT),
	.B2(G101GAT),
	.ZN(top_n_288));
   AOI21_X1 g46157 (.A(bottom_g46157_A),
	.B1(bottom_g46187_ZN),
	.B2(G96GAT),
	.ZN(bottom_g46157_ZN));
   OAI21_X1 g46160 (.A(top_n_291),
	.B1(bottom_g46281_ZN),
	.B2(bottom_g46160_B2),
	.ZN(bottom_g46160_ZN));
   XNOR2_X1 g46152 (.A(top_n_292),
	.B(G165GAT),
	.ZN(top_n_289));
   NAND2_X1 g46168 (.A1(bottom_g46187_ZN),
	.A2(G126GAT),
	.ZN(bottom_g46168_ZN));
   AOI221_X1 g46177 (.A(bottom_g46177_A),
	.B1(G138GAT),
	.B2(G152GAT),
	.C1(bottom_g46208_ZN),
	.C2(G153GAT),
	.ZN(top_n_291));
   XNOR2_X1 g46181 (.A(bottom_g46181_A),
	.B(G135GAT),
	.ZN(bottom_g46181_ZN));
   XNOR2_X1 g46184 (.A(top_n_293),
	.B(G189GAT),
	.ZN(top_n_290));
   INV_X1 g46187 (.A(bottom_g46281_ZN),
	.ZN(bottom_g46187_ZN));
   NAND4_X1 g46195 (.A1(top_n_294),
	.A2(top_n_295),
	.A3(G72GAT),
	.A4(G73GAT),
	.ZN(bottom_g46195_ZN));
   OAI211_X1 g46175 (.A(bottom_g46175_A),
	.B(top_n_296),
	.C1(bottom_g46208_A),
	.C2(bottom_g46175_C2),
	.ZN(bottom_g46175_ZN));
   XNOR2_X1 g46182 (.A(top_n_297),
	.B(G130GAT),
	.ZN(top_n_292));
   AND3_X1 g46193 (.A1(top_n_294),
	.A2(G59GAT),
	.A3(G74GAT),
	.ZN(G449GAT));
   NOR2_X1 g46192 (.A1(top_n_298),
	.A2(bottom_g46259_ZN),
	.ZN(G448GAT));
   AOI21_X1 g46191 (.A(bottom_g46215_A2),
	.B1(bottom_g46191_B1),
	.B2(bottom_g46251_ZN),
	.ZN(bottom_g46191_ZN));
   NAND3_X1 g46197 (.A1(bottom_g46197_A1),
	.A2(G447GAT),
	.A3(G55GAT),
	.ZN(bottom_g46197_ZN));
   XNOR2_X1 g46200 (.A(top_n_299),
	.B(G195GAT),
	.ZN(top_n_293));
   INV_X1 g46206 (.A(top_n_298),
	.ZN(top_n_294));
   INV_X1 g46208 (.A(bottom_g46208_A),
	.ZN(bottom_g46208_ZN));
   XNOR2_X1 g46201 (.A(top_n_300),
	.B(G171GAT),
	.ZN(top_n_297));
   XNOR2_X1 g46202 (.A(bottom_g46202_A),
	.B(G101GAT),
	.ZN(bottom_g46202_ZN));
   NAND3_X1 g46207 (.A1(bottom_g46207_A1),
	.A2(G55GAT),
	.A3(G68GAT),
	.ZN(top_n_298));
   NAND2_X1 g46205 (.A1(bottom_g46226_ZN),
	.A2(bottom_g46230_ZN),
	.ZN(G419GAT));
   AOI211_X1 g46210 (.A(bottom_g46210_A),
	.B(bottom_g46254_ZN),
	.C1(bottom_g46210_C1),
	.C2(G59GAT),
	.ZN(top_n_301));
   OAI211_X1 g46232 (.A(G26GAT),
	.B(G156GAT),
	.C1(bottom_g46232_C1),
	.C2(top_n_302),
	.ZN(bottom_g46232_ZN));
   NAND2_X1 g46213 (.A1(top_n_295),
	.A2(G36GAT),
	.ZN(G422GAT));
   NOR2_X1 g46215 (.A1(bottom_g46215_A1),
	.A2(bottom_g46215_A2),
	.ZN(G447GAT));
   AOI22_X1 g46236 (.A1(bottom_g46236_A1),
	.A2(G183GAT),
	.B1(bottom_g46236_B1),
	.B2(G201GAT),
	.ZN(top_n_299));
   NOR2_X1 g46226 (.A1(bottom_g46226_A1),
	.A2(top_n_303),
	.ZN(bottom_g46226_ZN));
   XNOR2_X1 g46237 (.A(bottom_g46237_A),
	.B(G126GAT),
	.ZN(bottom_g46237_ZN));
   AND2_X1 g46212 (.A1(top_n_304),
	.A2(G89GAT),
	.ZN(G450GAT));
   AND2_X1 g46214 (.A1(top_n_304),
	.A2(G90GAT),
	.ZN(G423GAT));
   INV_X1 g46240 (.A(bottom_g46240_A),
	.ZN(bottom_g46240_ZN));
   OAI21_X1 g46221 (.A(G59GAT),
	.B1(G17GAT),
	.B2(G42GAT),
	.ZN(bottom_g46221_ZN));
   AOI21_X1 g46222 (.A(G246GAT),
	.B1(G159GAT),
	.B2(G237GAT),
	.ZN(top_n_287));
   NAND3_X1 g46228 (.A1(G1GAT),
	.A2(G8GAT),
	.A3(G13GAT),
	.ZN(bottom_g46228_ZN));
   NAND3_X1 g46230 (.A1(G42GAT),
	.A2(G29GAT),
	.A3(G36GAT),
	.ZN(bottom_g46230_ZN));
   XNOR2_X1 g46234 (.A(G116GAT),
	.B(G111GAT),
	.ZN(bottom_g46234_ZN));
   XOR2_X1 g46235 (.A(G177GAT),
	.B(G159GAT),
	.Z(top_n_300));
   NOR2_X1 g46248 (.A1(bottom_g46248_A1),
	.A2(top_n_302),
	.ZN(top_n_295));
   NAND2_X1 g46250 (.A1(G138GAT),
	.A2(G51GAT),
	.ZN(bottom_g46250_ZN));
   NAND2_X1 g46251 (.A1(G59GAT),
	.A2(G156GAT),
	.ZN(bottom_g46251_ZN));
   OR2_X1 g46253 (.A1(G87GAT),
	.A2(G88GAT),
	.ZN(top_n_304));
   AND2_X1 g46257 (.A1(G85GAT),
	.A2(G86GAT),
	.ZN(G391GAT));
   NAND2_X1 g46254 (.A1(G1GAT),
	.A2(G51GAT),
	.ZN(bottom_g46254_ZN));
   NAND2_X1 g46249 (.A1(G17GAT),
	.A2(G138GAT),
	.ZN(top_n_296));
   NAND2_X1 g46241 (.A1(G75GAT),
	.A2(G80GAT),
	.ZN(bottom_g46241_ZN));
   NAND2_X1 g46242 (.A1(G13GAT),
	.A2(G26GAT),
	.ZN(top_n_303));
   INV_X1 g46273 (.A(G165GAT),
	.ZN(bottom_g46273_ZN));
   INV_X1 g46260 (.A(G228GAT),
	.ZN(top_n_284));
   INV_X1 g46271 (.A(G219GAT),
	.ZN(bottom_g46271_ZN));
   INV_X1 g46259 (.A(G29GAT),
	.ZN(bottom_g46259_ZN));
   INV_X1 g46258 (.A(G42GAT),
	.ZN(top_n_302));
   INV_X1 g46276 (.A(G153GAT),
	.ZN(bottom_g46276_ZN));
   INV_X1 g46275 (.A(G237GAT),
	.ZN(bottom_g46275_ZN));
   INV_X1 g46270 (.A(G246GAT),
	.ZN(bottom_g46270_ZN));
   INV_X1 g46264 (.A(G146GAT),
	.ZN(bottom_g46264_ZN));
   NOR2_X1 g46281 (.A1(bottom_g46281_A1),
	.A2(top_n_301),
	.ZN(bottom_g46281_ZN));
endmodule

