/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID aduae260-lap)
#  Generated on:      Wed Sep 26 11:40:53 2018
#  Design:            c880
#  Command:           saveNetlist -module c880 outputs/wrapper_j.v
###############################################################
*/
module c880 (
	G1GAT, 
	G8GAT, 
	G13GAT, 
	G17GAT, 
	G26GAT, 
	G29GAT, 
	G36GAT, 
	G42GAT, 
	G51GAT, 
	G55GAT, 
	G59GAT, 
	G68GAT, 
	G72GAT, 
	G73GAT, 
	G74GAT, 
	G75GAT, 
	G80GAT, 
	G85GAT, 
	G86GAT, 
	G87GAT, 
	G88GAT, 
	G89GAT, 
	G90GAT, 
	G91GAT, 
	G96GAT, 
	G101GAT, 
	G106GAT, 
	G111GAT, 
	G116GAT, 
	G121GAT, 
	G126GAT, 
	G130GAT, 
	G135GAT, 
	G138GAT, 
	G143GAT, 
	G146GAT, 
	G149GAT, 
	G152GAT, 
	G153GAT, 
	G156GAT, 
	G159GAT, 
	G165GAT, 
	G171GAT, 
	G177GAT, 
	G183GAT, 
	G189GAT, 
	G195GAT, 
	G201GAT, 
	G207GAT, 
	G210GAT, 
	G219GAT, 
	G228GAT, 
	G237GAT, 
	G246GAT, 
	G255GAT, 
	G259GAT, 
	G260GAT, 
	G261GAT, 
	G267GAT, 
	G268GAT, 
	G388GAT, 
	G389GAT, 
	G390GAT, 
	G391GAT, 
	G418GAT, 
	G419GAT, 
	G420GAT, 
	G421GAT, 
	G422GAT, 
	G423GAT, 
	G446GAT, 
	G447GAT, 
	G448GAT, 
	G449GAT, 
	G450GAT, 
	G767GAT, 
	G768GAT, 
	G850GAT, 
	G863GAT, 
	G864GAT, 
	G865GAT, 
	G866GAT, 
	G874GAT, 
	G878GAT, 
	G879GAT, 
	G880GAT);
   input G1GAT;
   input G8GAT;
   input G13GAT;
   input G17GAT;
   input G26GAT;
   input G29GAT;
   input G36GAT;
   input G42GAT;
   input G51GAT;
   input G55GAT;
   input G59GAT;
   input G68GAT;
   input G72GAT;
   input G73GAT;
   input G74GAT;
   input G75GAT;
   input G80GAT;
   input G85GAT;
   input G86GAT;
   input G87GAT;
   input G88GAT;
   input G89GAT;
   input G90GAT;
   input G91GAT;
   input G96GAT;
   input G101GAT;
   input G106GAT;
   input G111GAT;
   input G116GAT;
   input G121GAT;
   input G126GAT;
   input G130GAT;
   input G135GAT;
   input G138GAT;
   input G143GAT;
   input G146GAT;
   input G149GAT;
   input G152GAT;
   input G153GAT;
   input G156GAT;
   input G159GAT;
   input G165GAT;
   input G171GAT;
   input G177GAT;
   input G183GAT;
   input G189GAT;
   input G195GAT;
   input G201GAT;
   input G207GAT;
   input G210GAT;
   input G219GAT;
   input G228GAT;
   input G237GAT;
   input G246GAT;
   input G255GAT;
   input G259GAT;
   input G260GAT;
   input G261GAT;
   input G267GAT;
   input G268GAT;
   output G388GAT;
   output G389GAT;
   output G390GAT;
   output G391GAT;
   output G418GAT;
   output G419GAT;
   output G420GAT;
   output G421GAT;
   output G422GAT;
   output G423GAT;
   output G446GAT;
   output G447GAT;
   output G448GAT;
   output G449GAT;
   output G450GAT;
   output G767GAT;
   output G768GAT;
   output G850GAT;
   output G863GAT;
   output G864GAT;
   output G865GAT;
   output G866GAT;
   output G874GAT;
   output G878GAT;
   output G879GAT;
   output G880GAT;

   // Internal wires
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_14;
   wire n_15;
   wire n_17;
   wire n_19;
   wire n_21;
   wire n_24;
   wire n_26;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_37;
   wire n_38;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_55;
   wire n_57;
   wire n_58;
   wire n_60;
   wire n_63;
   wire n_65;
   wire n_66;
   wire n_70;
   wire n_71;
   wire n_74;
   wire n_78;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_87;
   wire n_88;
   wire n_91;
   wire n_93;
   wire n_95;
   wire n_99;
   wire n_100;
   wire n_102;
   wire n_106;
   wire n_109;
   wire n_110;
   wire n_112;
   wire n_113;
   wire n_117;
   wire n_119;
   wire n_120;
   wire n_122;
   wire n_124;
   wire n_125;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_160;
   wire n_164;
   wire n_166;
   wire n_167;
   wire n_169;
   wire n_170;
   wire n_172;
   wire n_173;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_180;
   wire n_181;
   wire n_183;
   wire n_184;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_200;
   wire n_204;
   wire n_206;
   wire n_207;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_215;
   wire n_217;
   wire n_282;

   bottom bottom (.G1GAT(G1GAT),
	.G8GAT(G8GAT),
	.G17GAT(G17GAT),
	.G26GAT(G26GAT),
	.G29GAT(G29GAT),
	.G36GAT(G36GAT),
	.G42GAT(G42GAT),
	.G51GAT(G51GAT),
	.G55GAT(G55GAT),
	.G59GAT(G59GAT),
	.G75GAT(G75GAT),
	.G80GAT(G80GAT),
	.G91GAT(G91GAT),
	.G96GAT(G96GAT),
	.G101GAT(G101GAT),
	.G106GAT(G106GAT),
	.G111GAT(G111GAT),
	.G116GAT(G116GAT),
	.G121GAT(G121GAT),
	.G130GAT(G130GAT),
	.G138GAT(G138GAT),
	.G143GAT(G143GAT),
	.G149GAT(G149GAT),
	.G159GAT(G159GAT),
	.G165GAT(G165GAT),
	.G171GAT(G171GAT),
	.G177GAT(G177GAT),
	.G183GAT(G183GAT),
	.G189GAT(G189GAT),
	.G195GAT(G195GAT),
	.G201GAT(G201GAT),
	.G207GAT(G207GAT),
	.G210GAT(G210GAT),
	.G219GAT(G219GAT),
	.G228GAT(G228GAT),
	.G237GAT(G237GAT),
	.G246GAT(G246GAT),
	.G255GAT(G255GAT),
	.G260GAT(G260GAT),
	.G261GAT(G261GAT),
	.G267GAT(G267GAT),
	.G268GAT(G268GAT),
	.g46069_ZN(n_217),
	.g46072_ZN(n_215),
	.g46077_ZN(n_197),
	.g46127_ZN(n_195),
	.g46067_ZN(n_211),
	.g46098_ZN(n_176),
	.g46109_CO(n_131),
	.g46074_ZN(n_204),
	.g46271_ZN(n_206),
	.g46097_ZN(n_181),
	.g46084_ZN(n_192),
	.g46085_ZN(n_191),
	.g46109_S(n_175),
	.g46092_ZN(n_190),
	.g46103_ZN(n_188),
	.g46093_ZN(n_178),
	.g46112_ZN(n_184),
	.g46119_ZN(n_170),
	.g46124_ZN(n_158),
	.g46111_ZN(n_167),
	.g46125_ZN(n_172),
	.g46091_ZN(n_156),
	.g46129_ZN(n_160),
	.g46150_ZN(n_152),
	.g46117_ZN(n_148),
	.g46139_ZN(n_143),
	.g46275_ZN(n_154),
	.g46270_ZN(n_147),
	.g46135_ZN(n_150),
	.g46148_ZN(n_128),
	.g46176_ZN(n_113),
	.g46160_ZN(n_120),
	.g46122_ZN(n_112),
	.g46142_ZN(n_142),
	.g46157_ZN(n_117),
	.g46273_ZN(n_8),
	.g46168_ZN(n_109),
	.g46187_ZN(n_91),
	.g46181_ZN(n_93),
	.g46175_ZN(n_85),
	.g46197_ZN(n_102),
	.g46281_ZN(n_282),
	.g46191_ZN(n_87),
	.g46264_ZN(n_81),
	.g46195_ZN(n_99),
	.g46208_ZN(n_88),
	.g46276_ZN(n_3),
	.g46250_ZN(n_15),
	.g46202_ZN(n_66),
	.g46232_ZN(n_57),
	.g46221_ZN(n_29),
	.g46254_ZN(n_58),
	.g46215_ZN(G447GAT),
	.g46237_ZN(n_38),
	.g46234_ZN(n_24),
	.g46251_ZN(n_65),
	.g46226_ZN(n_60),
	.g46228_ZN(n_43),
	.g46240_ZN(n_31),
	.g46259_ZN(n_49),
	.g46230_ZN(n_42),
	.g46241_ZN(n_21),
	.G388GAT(G388GAT),
	.G389GAT(G389GAT),
	.G390GAT(G390GAT),
	.G418GAT(G418GAT),
	.G420GAT(G420GAT),
	.G421GAT(G421GAT),
	.G446GAT(G446GAT),
	.G767GAT(G767GAT),
	.G768GAT(G768GAT),
	.G850GAT(G850GAT),
	.G866GAT(G866GAT),
	.G874GAT(G874GAT),
	.G878GAT(G878GAT),
	.G879GAT(G879GAT),
	.G880GAT(G880GAT),
	.g46067_A(n_207),
	.g46075_A1(n_200),
	.g46077_A1(n_196),
	.g46078_B1(n_189),
	.g46085_A(n_183),
	.g46089_A(n_173),
	.g46093_A(n_177),
	.g46089_C1(n_164),
	.g46078_A(n_157),
	.g46119_A(n_155),
	.g46092_A1(n_180),
	.g46071_C2(n_151),
	.g46071_A(n_136),
	.g46074_A2(n_169),
	.g46097_B2(n_166),
	.g46091_B1(n_213),
	.g46111_A(n_127),
	.g46127_A2(n_212),
	.g46127_A1(n_134),
	.g46138_A(n_125),
	.g46126_A1(n_141),
	.g46125_A1(n_149),
	.g46139_A1(n_124),
	.g46124_B1(n_110),
	.g46085_B1(n_130),
	.g46148_A1(n_122),
	.g46109_A(n_138),
	.g46150_A1(n_129),
	.g46118_B1(n_119),
	.g46165_A(n_106),
	.g46118_A(n_100),
	.g46178_A1(n_135),
	.g46124_B2(n_95),
	.g46157_A(n_83),
	.g46177_A(n_74),
	.g46281_A1(n_78),
	.g46175_A(n_84),
	.g46181_A(n_70),
	.g46208_A(n_82),
	.g46191_B1(n_48),
	.g46207_A1(n_44),
	.g46197_A1(n_71),
	.g46202_A(n_26),
	.g46129_A2(n_19),
	.g46131_A(n_17),
	.g46215_A1(n_47),
	.g46210_C1(n_32),
	.g46240_A(n_30),
	.g46210_A(n_14),
	.g46226_A1(n_41),
	.g46248_A1(n_7),
	.g46160_B2(n_6),
	.g46175_C2(n_5),
	.g46237_A(n_37),
	.g46236_A1(n_45),
	.g46232_C1(n_55),
	.g46215_A2(n_63),
	.g46109_B(n_137),
	.g46142_A2(n_2),
	.g46236_B1(n_1));
   top top (.G1GAT(G1GAT),
	.G8GAT(G8GAT),
	.G13GAT(G13GAT),
	.G17GAT(G17GAT),
	.G26GAT(G26GAT),
	.G29GAT(G29GAT),
	.G36GAT(G36GAT),
	.G42GAT(G42GAT),
	.G51GAT(G51GAT),
	.G55GAT(G55GAT),
	.G59GAT(G59GAT),
	.G68GAT(G68GAT),
	.G72GAT(G72GAT),
	.G73GAT(G73GAT),
	.G74GAT(G74GAT),
	.G75GAT(G75GAT),
	.G80GAT(G80GAT),
	.G85GAT(G85GAT),
	.G86GAT(G86GAT),
	.G87GAT(G87GAT),
	.G88GAT(G88GAT),
	.G89GAT(G89GAT),
	.G90GAT(G90GAT),
	.G96GAT(G96GAT),
	.G101GAT(G101GAT),
	.G111GAT(G111GAT),
	.G116GAT(G116GAT),
	.G126GAT(G126GAT),
	.G130GAT(G130GAT),
	.G135GAT(G135GAT),
	.G138GAT(G138GAT),
	.G146GAT(G146GAT),
	.G152GAT(G152GAT),
	.G153GAT(G153GAT),
	.G156GAT(G156GAT),
	.G159GAT(G159GAT),
	.G165GAT(G165GAT),
	.G171GAT(G171GAT),
	.G177GAT(G177GAT),
	.G183GAT(G183GAT),
	.G189GAT(G189GAT),
	.G195GAT(G195GAT),
	.G201GAT(G201GAT),
	.G210GAT(G210GAT),
	.G219GAT(G219GAT),
	.G228GAT(G228GAT),
	.G237GAT(G237GAT),
	.G246GAT(G246GAT),
	.G255GAT(G255GAT),
	.G259GAT(G259GAT),
	.G261GAT(G261GAT),
	.bottom_g46091_B1(n_213),
	.bottom_g46127_A2(n_212),
	.bottom_g46067_A(n_207),
	.bottom_g46071_A(n_136),
	.bottom_g46071_C2(n_151),
	.bottom_g46078_A(n_157),
	.bottom_g46078_B1(n_189),
	.bottom_g46075_A1(n_200),
	.bottom_g46127_A1(n_134),
	.bottom_g46077_A1(n_196),
	.bottom_g46074_A2(n_169),
	.bottom_g46085_A(n_183),
	.bottom_g46085_B1(n_130),
	.bottom_g46089_A(n_173),
	.bottom_g46089_C1(n_164),
	.bottom_g46092_A1(n_180),
	.bottom_g46150_A1(n_129),
	.bottom_g46093_A(n_177),
	.bottom_g46119_A(n_155),
	.bottom_g46097_B2(n_166),
	.bottom_g46111_A(n_127),
	.bottom_g46125_A1(n_149),
	.bottom_g46126_A1(n_141),
	.bottom_g46118_A(n_100),
	.bottom_g46118_B1(n_119),
	.bottom_g46124_B1(n_110),
	.bottom_g46124_B2(n_95),
	.bottom_g46148_A1(n_122),
	.bottom_g46178_A1(n_135),
	.bottom_g46131_A(n_17),
	.bottom_g46109_A(n_138),
	.bottom_g46109_B(n_137),
	.bottom_g46138_A(n_125),
	.bottom_g46139_A1(n_124),
	.bottom_g46129_A2(n_19),
	.bottom_g46142_A2(n_2),
	.bottom_g46165_A(n_106),
	.bottom_g46157_A(n_83),
	.bottom_g46160_B2(n_6),
	.bottom_g46177_A(n_74),
	.bottom_g46181_A(n_70),
	.bottom_g46175_A(n_84),
	.bottom_g46208_A(n_82),
	.bottom_g46175_C2(n_5),
	.bottom_g46215_A2(n_63),
	.bottom_g46191_B1(n_48),
	.bottom_g46197_A1(n_71),
	.bottom_g46202_A(n_26),
	.bottom_g46207_A1(n_44),
	.bottom_g46210_A(n_14),
	.bottom_g46210_C1(n_32),
	.bottom_g46232_C1(n_55),
	.bottom_g46215_A1(n_47),
	.bottom_g46236_A1(n_45),
	.bottom_g46236_B1(n_1),
	.bottom_g46226_A1(n_41),
	.bottom_g46237_A(n_37),
	.bottom_g46240_A(n_30),
	.bottom_g46248_A1(n_7),
	.bottom_g46281_A1(n_78),
	.G391GAT(G391GAT),
	.G419GAT(G419GAT),
	.G422GAT(G422GAT),
	.G423GAT(G423GAT),
	.G447GAT(G447GAT),
	.G448GAT(G448GAT),
	.G449GAT(G449GAT),
	.G450GAT(G450GAT),
	.G863GAT(G863GAT),
	.G864GAT(G864GAT),
	.G865GAT(G865GAT),
	.bottom_g46069_ZN(n_217),
	.bottom_g46072_ZN(n_215),
	.bottom_g46067_ZN(n_211),
	.bottom_g46074_ZN(n_204),
	.bottom_g46077_ZN(n_197),
	.bottom_g46084_ZN(n_192),
	.bottom_g46085_ZN(n_191),
	.bottom_g46092_ZN(n_190),
	.bottom_g46093_ZN(n_178),
	.bottom_g46098_ZN(n_176),
	.bottom_g46103_ZN(n_188),
	.bottom_g46119_ZN(n_170),
	.bottom_g46097_ZN(n_181),
	.bottom_g46091_ZN(n_156),
	.bottom_g46112_ZN(n_184),
	.bottom_g46117_ZN(n_148),
	.bottom_g46124_ZN(n_158),
	.bottom_g46125_ZN(n_172),
	.bottom_g46109_CO(n_131),
	.bottom_g46109_S(n_175),
	.bottom_g46127_ZN(n_195),
	.bottom_g46129_ZN(n_160),
	.bottom_g46135_ZN(n_150),
	.bottom_g46111_ZN(n_167),
	.bottom_g46139_ZN(n_143),
	.bottom_g46142_ZN(n_142),
	.bottom_g46148_ZN(n_128),
	.bottom_g46150_ZN(n_152),
	.bottom_g46176_ZN(n_113),
	.bottom_g46122_ZN(n_112),
	.bottom_g46157_ZN(n_117),
	.bottom_g46160_ZN(n_120),
	.bottom_g46168_ZN(n_109),
	.bottom_g46181_ZN(n_93),
	.bottom_g46187_ZN(n_91),
	.bottom_g46195_ZN(n_99),
	.bottom_g46175_ZN(n_85),
	.bottom_g46191_ZN(n_87),
	.bottom_g46197_ZN(n_102),
	.bottom_g46208_ZN(n_88),
	.bottom_g46202_ZN(n_66),
	.bottom_g46232_ZN(n_57),
	.bottom_g46226_ZN(n_60),
	.bottom_g46237_ZN(n_38),
	.bottom_g46240_ZN(n_31),
	.bottom_g46221_ZN(n_29),
	.bottom_g46228_ZN(n_43),
	.bottom_g46230_ZN(n_42),
	.bottom_g46234_ZN(n_24),
	.bottom_g46250_ZN(n_15),
	.bottom_g46251_ZN(n_65),
	.bottom_g46254_ZN(n_58),
	.bottom_g46241_ZN(n_21),
	.bottom_g46273_ZN(n_8),
	.bottom_g46271_ZN(n_206),
	.bottom_g46259_ZN(n_49),
	.bottom_g46276_ZN(n_3),
	.bottom_g46275_ZN(n_154),
	.bottom_g46270_ZN(n_147),
	.bottom_g46264_ZN(n_81),
	.bottom_g46281_ZN(n_282));
endmodule

